[[integration-solution-design]]
= Solution design

This section descibes the generic guidelines for integration solution design.

== Microservices

== Connectivity

[#281]
=== {STATUS-RFP} {MUST} have self-healing connectivity

External connections (e.g. SFTP, Database, SAP or Email) need to be
<<282,monitored>> and automatically reset and restored when connection issues
occur. The frequency for these reconnections and after how many retries to send
an alert needs to be agreed upon with the business. 

However, if no such agreements are in place, we set as default to retry once
every minute and send an alert when reconnection has failed for an hour. After
the alert has been sent, reconnection attempts must continue until successful.


[#283]
=== {STATUS-RFP} {SHOULD} have increasing reconnection intervals

When reconnection strategies are deployed they should have increasing
reconnection intervals. For example 1s, 2s, 4s etc.

== Loosely coupled

== Security

== Monitoring

[#282]
=== {STATUS-RFP} {MUST} setup monitoring and alerting connections

All connections must be monitored and alerting has to be setup based on the
monitoring.

== Documentation

== Security


