[[quality]]
= Quality

[#294]
== {STATUS-RFP} {SHOULD} have seperate environments for development, testing, acceptance and production

In order to maintain software or integration quality the setup of an DTAP
environment is preferred. This setup allows for an atomized way of working on
features and bug fixes. These environments should be available before starting
development.

This environment consists of four parts:

=== Development

The development environment is used for the actual development or for example
bug fixing.

=== Testing

The testing environment is the first step for quality assurance, in this
environment the automated or manual tests are done to confirm new
functionalities or bug fixes. Note there can be several testing environments,
eg: an environment for the testing of an operational bug and an environment for
the testing of a new feature.

=== Acceptance

The acceptance environment is the second step for quality assurance, this
environment allows for the customer to confirm new functionalities or bug fixes.
In this environment several updates can be combined to prepare for a deployment
to the production systems.

This environment allows for the customer to sign of on the development.

=== Production

The primary environment for production. This environment can only be updated
after a signoff of which the requirements are specified beforehand.

== Code Quality

The quality of the code should be known, but we diffrentiate between frontends and microservices. GUI are more difficult to test, because you'll need to automate the click flow through the frontend/GUI and therefor more labour intensive to maintain.

All tests should be configured in the pipeline so the developer receives instant feedback of the commit.

[#299]
=== {STATUS-RFP} {MUST} have duplication tests defined

A software project must have something in place to detect duplicated code.

[#300]
==== {STATUS-RFP} {MUST} have vulnerability checks
When running in the pipline a vulnerability check must happen, so comprimised libraries are not taken into production.

=== GUI and Websites

[#297]
==== {STATUS-RFP} {SHOULD} have predefined tests
A GUI project should have some tests defined, for example; a webshop should be able to have an item in the cart and finalize the checkout.


=== API's

API's need to have a certain quality level what can be observed.

[#276]
==== {STATUS-RFP} {MUST} have predefined tests

Unit / feature / e2e tests need to be available.

[#298]
==== {STATUS-RFP} {MUST} have a pre-defined code-coverage percentage

An API must have a pre-defined level of code-coverage. This tells something about how well the code is tested and if all code paths have been checked.