# this is how you configure zappr
# a more exhaustive description is at
# https://zappr.readthedocs.io/en/latest/setup

# Every PR needs two approvals from Zalando employees.
approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          # Only "zalando" allowed here!
          - zalando

X-Zalando-Team: architecture
X-Zalando-Type: code
