= Developing Restful APIs: A Comprehensive Set of Guidelines. Originally created by Zalando.

== Purpose

Great RESTful APIs look like they were designed by a single team. This
promotes API adoption, reduces friction, and enables clients to use them
properly. To build APIs that meet this standard, and to answer many
common questions encountered along the way of RESTful API development,
the Zalando Tech team has created this comprehensive set of guidelines.

The NUPANO dev leads have decided to take the original guidelines from Zalando 
and adapt them four NUPANO needs. Mainly this means only small renamings and  adjustments in priority.

Probs

== Usage

See link:BUILD.adoc[BUILD documentation] for technical details.

== License

We have published these guidelines under the CC-BY (Creative commons
Attribution 4.0) license. Please see link:LICENSE[LICENSE file].

== NUPANO related changes

- zappr (https://github.com/zalando/zappr) config removed
- API audience removed
-- #219 provide API audience
- internationalized data formats removed (#238)
- Zalando specific JSON Guideline details removed
- rule 249 (use the common address fields) removed
- rule 173 (use the common money object) removed
- rule 183 (use only the specified proprietary Zalando headers) removed
- rule 184 (propagate prorietary headers) removed