= Developing Restful APIs: A Comprehensive Set of Guidelines by DailyPay


https://github.com/dailypay/restful-api-guidelines/actions/[image:https://github.com/dailypay/restful-api-guidelines/actions/workflows/build.yml/badge.svg[Build status]]
Latest published version:
https://github.com/dailypay/restful-api-guidelines/[*HTML*],
https://github.com/dailypay/restful-api-guidelines/dailypay-guidelines.pdf[*PDF*],
https://github.com/dailypay/restful-api-guidelines/gailypay-guidelines.epub[*EPUB3*]

== Purpose

Great RESTful APIs look like they were designed by a single team. This
promotes API adoption, reduces friction, and enables clients to use them
properly. To build APIs that meet this standard, and to answer many
common questions encountered along the way of RESTful API development,
the DailyPay Tech team has created this comprehensive set of guidelines.
We have shared it with you to inspire additional discussion and
refinement within and among your teams, and contribute our learnings and
suggestions to the tech community at large.

== Usage

Feel free to use these guidelines as a guidance for your own
development. Note that we encourage our own teams to use them in order
to challenge their APIs. As such, you should consider this to be a
living, evolving document. We will revise and update based on our
learnings and experiences.

See link:BUILD.adoc[BUILD documentation] for technical details.

== Attribution

This Guideline has been adapted and modified from source material created by
https://corporate.zalando.com[Zalando SE]. Thank you to the
https://opensource.zalando.com[Zalando Open Source Team]
for sharing their
https://opensource.zalando.com/restful-api-guidelines[Zalando API Guidelines].
This Guideline is derived from their work and DailyPay appreciates their
contribution and willingness to share.

== License

We have published these guidelines under the CC-BY (Creative commons
Attribution 4.0) license. Please see link:LICENSE[LICENSE file].
