[[development-guidelines]]
= General development guidelines

[[fowler-quote-01]]
[quote, M. Fowler (1999)]     
____ 
Any fool can write code that a computer can understand. Good programmers write
code that humans can understand.
____

[[development-introduction]]
== Introduction

This chapter is about coding, developing or anything related to using a
programming language to solve a problem. 

[[pramatic-programmer-quote-collect-knowledge]]
[quote, Pragmatic Programmer, Page 61]
____
As programmers, we collect, organize, maintain, and harness knowledge. We
document knowledge in specifications, we make it come alive in running code, and
we use it to provide the checks needed during testing.
____

A problem is defined as a resolution for a challenge the business is facing. The
mission of a coder is to write ”good”, ”clean” and ”secure” code.  These terms
are ill-defined.

At Pon we consider code ”good”, ”clean” and ”secure” based on the following rule
of thumb

IMPORTANT: How much effort is required^<<244,244>>^ for another developer of
comparable experience to pick up where the previous developer left off to fix,
enhance or build upon the source code - without involving the former
developer^<<245,245>>^ and taking into account the lifetime, quality, security
and the business impact^<<246,246>>^ of the application.

There is a clear relationship between the amount of bugs in the code and the
development effort required, needlessly complex illogical code will in itself be
a source of new bugs. Moreover clear documentation and requirements from the
business are the only solid foundation for software development.

The following chapters will further explain the intricacies of this rule.

[[development-rules-definitions]]
== Rules and definitions

Rules and definition used in the development guidelines.

[#248]
== Definition: code quality

[[wikipedia-quote-software-quality]]
[quote, 'link:https://en.wikipedia.org/wiki/Software_quality[Wikipedia]']     
____
* Software functional quality reflects how well it complies with or conforms to
a given design, based on functional requirements or specifications.  That
attribute can also be described as the fitness for purpose of a piece of
software or how it compares to competitors in the marketplace as a worthwhile
product. It is the degree to which the correct software was produced.

* Software structural quality refers to how it meets non-functional requirements
that support the delivery of the functional requirements, such as robustness or
maintainability. It has a lot more to do with the degree to which the software
works as needed.
____

[#244]
== Coding rule: logical structured code

Refers to “_How much effort_”.

The amount of effort required for a change should be on-par with the apparent
complexity of the change.

A logical structure, both for files and in the code itself, is essential. This
also applies to the layout of the code itself, for example indents.

[TIP] 
.Updating an IP address
====
Updating the IP address of the database; small apparent complexity, small
effort required.

Good code will result in a single place to be updated. Clean code will result in
easy to find code to be updated.
====

[NOTE]
.Code layout
====
Code layout may differ greatly between projects, but within the same project all
files strictly adhere to the same code layout standards. Automated tools based
on <<solution-architecture-repository,accepted code style standards>> are
essential for enforcement.
====

[#254]
== Coding rule: code is simple and concise 

Refers to “_How much effort_”.

Code is simple and concise in order to increase the readability <<praeng>>, rule
4 <<nasa-safety-code>>. Increasing performance by sacrificing readability is
only an option if the performance increase is in-line with the business
requirements.

[[nasa-safety-code-rule-4]]
[quote, Nasa coding rules, Rule 4]
____
Rule: No function should be longer than what can be printed on a single sheet of
paper in a standard reference format with one line per statement and one line
per declaration. Typically, this means no more than about 60 lines of code per
function.

Rationale: Each function should be a logical unit in the code that is
understandable and verifiable as a unit. It is much harder to understand a
logical unit that spans multiple screens on a computer display or multiple pages
when printed. Excessively long functions are often a sign of poorly structured
code. 
____


[NOTE]
.Simple and concise
====
Based on the experience level of the developer simple and concise can easily
shift to unreadable and complex. Code should not be overly simplified in order
for all to understand, it is up to the lead developer to guide and train the
less experienced developers in writing and understanding simple and concise
code. 
====

[#258] 
== Coding rule: do not repeat yourself (DRY)

Refers to "_How much effort_".

[[wikipedia-quote-dry]]
[quote, 'link:https://en.wikipedia.org/wiki/Don%27t_repeat_yourself[Wikipedia]']     
____
Don't repeat yourself (DRY, or sometimes do not repeat yourself) is a principle
of software development aimed at reducing repetition of software patterns,
replacing it with abstractions or using data normalization to avoid redundancy.

The DRY principle is stated as "Every piece of knowledge must have a single,
unambiguous, authoritative representation within a system". The principle has
been formulated by Andy Hunt and Dave Thomas in their book The Pragmatic
Programmer. They apply it quite broadly to include "database schemas, test
plans, the build system, even documentation". When the DRY principle is
applied successfully, a modification of any single element of a system does not
require a change in other logically unrelated elements. Additionally, elements
that are logically related all change predictably and uniformly, and are thus
kept in sync.
____

Or, simply put:

[[pragmatic-programmer-quote-dry]]
[quote, Pragmatic Programmer, Page 62]
____
Every piece of knowledge must have a single, unambiguous, authoritative
representation within a system.
____

However keep in mind that if two distinct pieces of knowledge result in the same
code the DRY principle should be reviewed carefully as shown in
<<accidental-doppelganger>>

[NOTE]
====
The once and only once rule is one of the most fundamental principles of
software development, it can be seen as a hallmark of good and clean code and
will greatly reduce developer effort when applied correctly. But it is not the
goal of software development; the goal is resolving challenges of the business
under their conditions.

// Todo
Ref: https://gtramontina.com/posts/do-repeat-yourself.html
====

[#245]
== Coding rule: code and code changes are self-explanatory

Refers to “_without involving the previous developer_”.

All code is sufficiently documented in order to reduce the effort^<<244,244>>^
required for updates and changes. Comments must explain the why, not the how
<<praeng>>.

* Code changes are documented and should contain a reference to an issue
tracking system
* Deviation from guidelines is always documented

When readability is sacrificed for performance^<<254,254>>^ it is reflected in
the comments.

[NOTE]
====
Remember: while comments are very important, the best code is self-documenting.
Giving sensible names to types and variables is much better than using obscure
names that you must then explain through comments 
 
Ref: <<googleStyleguideCpp>>, #Comments
====

[#246]
== Coding rule: solution design steps are template-based

Refers to “_taking into account the lifetime, quality, security and business
impact_”.

Solution design comes first, coding second. The solution design must address the
following

* Software lifetime
* Required quality
* Required security
* Business impact

[#247]
== Coding rule: code quality is known

Based on the quality as discussed in the <<246, solution design>> steps the code
quality must be known.

This rule does not state that code must be fully automatically tested and
scoring 100/100 on quality. This rule states that the quality, as agreed upon
beforehand with the business, is known and documented.


[#264]
== Coding rule: cyclomatic complexity is low

Refers to “_How much effort_”.

Keep the number of conditional statements to a minimum; rule 1 of
<<nasa-safety-code>>. 

[[wikipedia-quote-cyclomatic-complexity]]
[quote, 'link:https://en.wikipedia.org/wiki/Cyclomatic_complexity[Wikipedia]']     
____

The cyclomatic complexity of a section of source code is the number of linearly
independent paths within it—where "linearly independent" means that each path
has at least one edge that is not in one of the other paths. For instance, if
the source code contained no control flow statements (conditionals or decision
points), the complexity would be 1, since there would be only a single path
through the code. If the code had one single-condition IF statement, there would
be two paths through the code: one where the IF statement evaluates to TRUE and
another one where it evaluates to FALSE, so the complexity would be 2. Two
nested single-condition IFs, or one IF with two conditions, would produce a
complexity of 3.
____

Only use an _else_ statement if required. Prefer a switch statement over
multiple if-then-else constructs.
