[[appendix-standard-style]]
[appendix]
= Pon Standard Style

Pon standard style can be applied when linters are not available.

Based on <<standardJs>>, <<googleStyleguideJs>>, <<phpStandards>>,
<<nasa-safety-code>> and <<gnu-coding-standards>>.

[#267]
== {MUST} encapsulate body of if or else

The body of an if or else must be encapsulated it increases readability and
decreases the introduction of bugs.

For single-line statements a ternary is preferred.

=== Example 1

[source,javascript]
----
if (a < b) 
  test(c)
load(b)

if (a < b) 
  //test(c)
load(b)
----

Commenting out one line for debugging purposes resulted in the addition of a new
bug, this can easily be avoid by using curly braces:

[source,javascript]
----
if (a < b) {
  test(c)
}
load(b)

if (a < b) {
  //test(c)
}
load(b)
----

=== Languages

{LANG-JAVASCRIPT-ICON} {LANG-TYPESCRIPT-ICON} {LANG-PHP-ICON} {LANG-GO-ICON}

[#253]
== {SHOULD} order if statements by increased complexity

If using if statements where the conditionals are related, they should be
ordered by increased complexity when possible. Using this ordering will
significantly improve readability.

=== Example 1

[source,javascript]
----
if (!invoicePaid && !email) {
  sendInvoiceByMail();
} else if (invoicePaid) {
  closeOrder();
}
----

By swapping the if statements the logic is more comfortable to follow:

[source,javascript]
----
if (invoicePaid) {
  closeOrder();
} else if (!invoicePaid && !email) {
  sendInvoiceByMail();
}
----


[#253]
== {MUST} use special quotes only to reduce complexity

In most programming languages several options are available for the quoting of
text, in the following examples Javascript style quoting is used which is
applicable to a variety of other programming languages.

For the following examples the key question is: can the readbility be improved
to make the code more simple and concise?

=== Example 1

[source,javascript]
----
text = "The quick brown fox jumped over the lazy dog"
----

Although the code is correct the double quotes have have no additional function,
the following code is more concise by using single quotes:

[source,javascript]
----
text = 'The quick brown fox jumped over the lazy dog'
----

=== Example 2

[source,javascript]
----
text = "The quick brown \"fox\" jumped over the lazy dog"
----

The code is correct, but readability is improved by switching to single quotes:

[source,javascript]
----
text = 'The quick brown "fox" jumped over the lazy dog'
----

=== Languages

{LANG-JAVASCRIPT-ICON} {LANG-TYPESCRIPT-ICON} {LANG-PHP-ICON}

=== References

* <<googleStyleguideJs>>, link:https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes[Use single quotes]
* <<standardJs>>, Use single quotes for strings 
* <<development-rules-definitions>>, <<244>>
* <<development-rules-definitions>>, <<254>>

[#257]
== {MUST} never use tabs for indentation

Tabs are never to be used for indentation.

=== Languages

{LANG-ALL-ICON}

=== References

* <<googleStyleguideJs>>, link:https://google.github.io/styleguide/jsguide.html#whitespace-characters[whitespace characters (2)]
* <<standardJs>>, Tabs should not be used
* <<phpStandards>>, link:https://www.php-fig.org/psr/psr-12/#24-indenting[indenting]
* <<development-rules-definitions>>, <<244>>
* <<development-rules-definitions>>, <<254>>


[#251]
== {MUST} use predefined spacing for indentation 

Using predefined spacing for indentation results in clear readable code without
sacrificing too much screen real estate; <<257>>.

When using multiple languages a single project it is preferred to use the same
indent for all languages involved.

=== Languages

==== {MUST} Spacing: 2
{LANG-JAVASCRIPT-ICON} {LANG-TYPESCRIPT-ICON} 

==== {SHOULD} Spacing: 2
{LANG-PHP-ICON}

==== {MAY} Spacing: 4
{LANG-PHP-ICON}

=== References

* <<googleStyleguideJs>>, link:https://google.github.io/styleguide/jsguide.html#whitespace-characters[whitespace characters (2)]
* <<standardJs>>, Use 2 spaces for indentation
* <<phpStandards>>, link:https://www.php-fig.org/psr/psr-12/#24-indenting[indenting]
* <<development-rules-definitions>>, <<244>>


[#265]
== {SHOULD} check return types of non-void functions

Return values of functions should not be ignored, especially if error return
values must be propagated up the function call chain. By checking return types
exception justification is enforced, which will result in increased code
stability.

=== Languages

{LANG-ALL-ICON}

== References

* <<nasa-safety-code>>, Rule 7


[#266]
== {SHOULD} check the validity of parameters inside each function

Input parameters should not be assumed to be valid; by checking the validity
code stability is increased.

=== Example 1

[source,javascript,linenums]
----
// Lodash - startsWith.js  - https://github.com/lodash/lodash
function startsWith(string, target, position) {
  const { length } = string
  position = position == null ? 0 : position
  if (position < 0) {
    position = 0
  }
  else if (position > length) {
    position = length
  }
  target = `${target}`
  return string.slice(position, position + target.length) == target
}
----

Note the majority of the code in example 1 is about checking the input
parameters. 

=== Languages

{LANG-ALL-ICON}

=== References

* <<nasa-safety-code>>, Rule 7
* http://en.wikipedia.org/wiki/Robustness_principle[The Robustness Principle] 


[#256]
== {MUST} not have unused variables

All variables are in use, unused variables have no function and are cluttering
the code.

=== Languages

{LANG-ALL-ICON}

=== References

* <<standardJs>>, No unused variables
* <<development-rules-definitions>>, <<244>>


[#262]
== {SHOULD} use < or > instead of +<=+ or >=

Using < is preferred over using +<=+, using > is preferred over using >=. It 
improves readability and performance of code.

=== Languages

{LANG-ALL-ICON}


[#263]
== {SHOULD} use != instead of > or < when only a single value results in false

If a return value always results in true except for a single value using != is
preferred over using > or >=.

=== Example 1

[source,javascript]
----
languages = ['NL', 'FR', 'BE'];

if (languages.indexOf('BE') >= 0)
----

The code is correct, but readability is reduced by using the >=, especially since
the return of the indexOf function is counterintuitive, a more readable solution
is:

[source,javascript]
----
languages = ['NL', 'FR', 'BE'];

if (languages.indexOf('BE') != -1)
----

=== Languages

{LANG-ALL-ICON}



