/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mkulak' at '12/19/16 11:45 AM' with Gradle 3.2.1
 *
 * @author mkulak, @date 12/19/16 11:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
