[[api-operation]]
= API Operation

[#192]
== {MUST} Publish OpenAPI Specification in Docker Artifacts

All service applications must publish OpenAPI specifications of their
external APIs. This is optional for internal APIs.

Publishing of APIs is done via Docker images as follows:

If the service provides one or more APIs::
Copy all API specifications into the `/zalando-apis` directory of the
Docker image of the service:

[source]
----
COPY my-api-1.yaml ... my-api-n.yaml /zalando-apis/
----

If the service does not provide any APIs::
Put an empty `no-apis` file into the `/zalando-apis` directory of the
Docker image of the service:

[source]
----
RUN mkdir /zalando-apis && touch /zalando-apis/no-apis
----

Please note that in the later case a shell has to be installed in the docker
container. Alternatively, you can create empty `no-apis` file locally and make
use of Docker `COPY` command in the Dockerfile.

We prefer the Docker image publishing method over the past (now legacy)
`.well-known/schema-discovery` service endpoint-based discovery process. However,
we currently support this way for backward compatibility reasons.

We distinguish between internal and external APIs of an application which is
owned by a specific team and often implemented via small set of services. An
external API is used by clients outside the team - usually another application
owned by a different team or even an external business partner. An internal
API is only used within the application and only by the owning team, for
instance, for operational or implementation internal purposes.

Background: In our dynamic and complex service infrastructure, it is important
to provide API client developers a central place with online access to the API
specifications of all running applications. As a part of the infrastructure,
the API discovery process is used to detect API specifications. It scans all
published Docker images and correlates API-related information with running
applications on AWS and Kubernetes clusters. The findings are published in the
API Portal - the universal hub for all Zalando APIs.

[#193]
== {SHOULD} Monitor API Usage

Owners of APIs used in production should monitor API service to get
information about its using clients. This information, for instance, is
useful to identify potential review partner for API changes.

Hint: A preferred way of client detection implementation is by logging
of the client-id retrieved from the OAuth token.
