[[api-operation]]
= REST Operation

[#192]
== {MUST} publish OpenAPI specification

All service applications must publish OpenAPI specifications of their external APIs.
This is done by an dedicated service which provides *all* OpenAPI specifications and a nice UI to browse them.

The development and release process is similar to other services. The content is located in a dedicated
repository (api-docs) and its build process produces a docker container which is published as all other services
in our infrastructure. The api-docs are available via "https://api-docs.nupano.com".

*Note*: Currently no code generation based the specs is in scope, neither for frond nor back end.


[#193]
== {MUST} monitor API usage

Owners of APIs used in production should monitor API service to get information about its using clients.
This information, for instance, is useful to identify potential review partner for API changes.

Hint: A preferred way of client detection implementation is by logging of the client-id retrieved from the OAuth token.
