[[api-operation]]
= REST Operation


[#192]
== {MUST} publish OpenAPI specification for APIs

All service applications must publish API Specifications of their external
APIs (see <<219, API Audience definition>>). While this is optional 
for <<219, component-internal>> APIs, we recommend doing so to profit from 
our API management infrastructure and review services.

As described in https://cloud.docs.zalando.net/howtos/api-publishing/[How to publish API Specifications (internal_link)], 
an API specification is published with the deployment of the implementing service 
by copying it to the reserved `/zalando-apis` directory. The directory must only 
contain _self-contained YAML files_ that each describe one API (exception see <<234>>). 
*Legacy hint:* We prefer this deployment artifact-based method over the old
`.well-known/schema-discovery` service endpoint-based publishing process
(which still is supported for backward compatibility).

*Motivation:* In our dynamic and complex service infrastructure, it is important
to provide API client developers a central place with online access to the API
specifications of all running applications. As a part of the infrastructure,
the API publishing process is used to detect API specifications and to make it 
discoverable via 
https://sunrise.zalando.net/apis?group=all[Sunrise (internal_link)] and the 
https://apis.zalando.net/[API Portal (internal_link)].

*Note:* APIs are discoverable only for recently running services. Hence, make sure 
to always publish the API Specification as part of the service artifact deployment. 


[#193]
== {SHOULD} monitor API usage

Owners of APIs used in production should monitor API service to get
information about its using clients. This information, for instance, is
useful to identify potential review partner for API changes.

Hint: A preferred way of client detection implementation is by logging
of the client-id retrieved from the OAuth token.
