[[api-operation]]
= API Operation

[#192]
== {MUST} Publish OpenAPI Specification

All service applications must publish OpenAPI specifications of their external
APIs. While this is optional for internal APIs, i.e. APIs marked with the
*component-internal* <<219, API audience>> group, we still recommend to do so
to profit from the API management infrastructure.

An API is published by copying its **OpenAPI specification** into the reserved
**/zalando-apis** directory of the **deployment artifact** used to deploy the
provisioning service. The directory must only contain **self-contained YAML**
**files** that each describe one API (see 
https://docs.google.com/a/zalando.de/document/d/1WBpRHp1DAtz7Pfjt0QwPuZNR1e70APRqUlCCby3JiOM[internal narrative]
for more details). We prefer this deployment artifact-based method over the
past (now legacy) `.well-known/schema-discovery` service endpoint-based
publishing process, that we only support for backward compatibility reasons.

Background: In our dynamic and complex service infrastructure, it is important
to provide API client developers a central place with online access to the API
specifications of all running applications. As a part of the infrastructure,
the API publishing process is used to detect API specifications. The findings
are published in the API Portal - the universal hub for all Zalando APIs.

[#193]
== {SHOULD} Monitor API Usage

Owners of APIs used in production should monitor API service to get
information about its using clients. This information, for instance, is
useful to identify potential review partner for API changes.

Hint: A preferred way of client detection implementation is by logging
of the client-id retrieved from the OAuth token.

