[[appendix-changelog]]
[appendix]
= Changelog

This change log only contains major changes made after October 2016.

Non-major changes are editorial-only changes or minor changes of existing guidelines, e.g. adding new error code.
Major changes are changes that come with additional obligations, or even change an existing guideline obligation.
The latter changes are additionally labeled with "Rule Change" here.

To see a list of all changes, please have a look at the https://github.com/zalando/restful-api-guidelines/commits/master[commit list in Github].

[[rule-changes]]
== Rule Changes

* `2019-01-24:` Improve guidance on caching (<<149>>, <<227>>). 
* `2019-01-15:` Improve guidance on idempotency, introduce idempotency-key (<<229>>, <<231>>).
* `2018-06-11:` Introduced new naming guidelines for host, permission, and event names.
* `2018-01-10:` Moved meta information related aspects into new chapter <<meta-information>>.
* `2018-01-09:` Changed publication requirements for API specifications (<<192>>).
* `2017-12-07:` Added best practices section including discussion about optimistic locking approaches.
* `2017-11-28:` Changed OAuth flow example from password to client credentials in <<security>>.
* `2017-11-22:` Updated description of X-Tenant-ID header field
* `2017-08-22:` Migration to Asciidoc
* `2017-07-20:` Be more precise on client vs. server obligations for compatible API extensions.
* `2017-06-06:` Made money object guideline clearer.
* `2017-05-17:` Added guideline on query parameter collection format.
* `2017-05-10:` Added the convention of using RFC2119 to describe guideline levels, and replaced `book.could` with `book.may`.
* `2017-03-30:` Added rule that permissions on resources in events must correspond to permissions on API resources
* `2017-03-30:` Added rule that APIs should be modelled around business processes
* `2017-02-28:` Extended information about how to reference sub-resources and the usage of composite identifiers in the <<143>>
part.
* `2017-02-22:` Added guidance for conditional requests with If-Match/If-None-Match
* `2017-02-02:` Added guideline for batch and bulk request
* `2017-02-01:` <<180>>
* `2017-01-18:` Removed "Avoid Javascript Keywords" rule
* `2017-01-05:` Clarification on the usage of the term "REST/RESTful"
* `2016-12-07:` Introduced "API as a Product" principle
* `2016-12-06:` New guideline: "Should Only Use UUIDs If Necessary"
* `2016-12-04:` Changed OAuth flow example from implicit to password in <<security>>.
* `2016-10-13:` <<172>>
* `2016-10-10:` Introduced the changelog. From now on all rule changes on API guidelines will be recorded here.

