[[deprecation]]
= Deprecation

Sometimes it is necessary to phase out an API endpoint, an API version, or an
API feature, e.g. if a field or parameter is no longer supported or a whole
business functionality behind an endpoint has to be shut down. As long as the
API endpoints and features are still used by consumers these shut downs are
breaking changes and not allowed. To progress the following deprecation rules
have to be applied to make sure that the necessary consumer changes are well
communicated and aligned.


[#185]
== {MUST} obtain approval of clients before API shut down

Before shutting down an API, version of an API, or API feature the producer
must make sure, that all clients have given their consent on a sunset date.
Producers should help consumers to migrate to a potential new API or API
feature by providing a migration manual and clearly state the time line for
replacement availability and sunsetting (see also <<189>>). After all clients
are migrated, the producer may shut down the deprecated API.


[#186]
== {MUST} external partners must agree on deprecation time span

If the API is consumed by any external partner, the producer must define
a reasonable time span that the API will be maintained after the producer
has announced deprecation. The external partner (client) must agree to
this minimum after-deprecation-life-span before he starts using the API.


[#187]
== {MUST} reflect deprecation in API specifications

The API deprecation must be part of the API specification.

If an API endpoint (operation object), an input argument (parameter object),
an in/out data object (schema object), or on a more fine grained level, a
schema attribute or property should be deprecated, the producers must set
`deprecated: true` for the affected element and add further explanation to the
`description` section of the API specification. The producer must provide a
sunset date in and describe what consumers should use instead, possibly
supported by links or references to more details.


[#188]
== {MUST} monitor usage of deprecated APIs and API endpoints

Owners of APIs used in production must monitor usage of deprecated APIs until
the API can be shut down in order to align deprecation and avoid uncontrolled
breaking effects. See also <<193>>.


[#189]
== {SHOULD} add `Deprecation` and `Sunset` header to responses

During the deprecation phase, the producer should add a `Deprecation: <date-time>`
(see https://tools.ietf.org/html/draft-dalal-deprecation-header[draft: RFC
Deprecation HTTP Header]) and a `Sunset: <date-time>` (see {RFC-8594}#section-3[RFC
8594]) header on each response affected by a deprecated element (see <<187>>).

The {Deprecation} header can either be set to `true` - if a feature is retired
-, or carry a deprecation time stamp, at which a replacement will become/became
available and consumers must not on-board any longer (see <<191>>). The optional
{Sunset} time stamp carries the information when consumers latest have to stop
using a feature and switch to a replacement solution. The sunset date should
always offer an eligible time interval for switching.

[source,txt]
----
Deprecation: Sun, 31 Dec 2024 23:59:59 GMT
Sunset: Sun, 31 Dec 2025 23:59:59 GMT
----

If multiple elements are deprecated the {Deprecation} and {Sunset} headers are
expected to be set to the earliest time stamp to reflect the shortest interval
consumers are expected to get active.

*Note:* adding the {Deprecation} and {Sunset} header is not sufficient to gain
client consent to shut down an API or feature.

*Hint:* In earlier guideline versions, we used the `Warning` header to provide
the deprecation info to clients. However, `Warning` header has a less specific
semantics, will be obsolete with 
https://tools.ietf.org/html/draft-ietf-httpbis-cache-06[draft: RFC HTTP
Caching], and our syntax was not compliant with {RFC-7234}#page-29[RFC 7234
-- Warning header].


[#190]
== {SHOULD} add monitoring for `Deprecation` and `Sunset` header

Clients should monitor the {Deprecation} and {Sunset} headers in HTTP responses
to get information about future sunset of APIs and API features (see <<189>>).
Based collected dates client owners should build alerts to ensure alignment
with service owners on required migration task.

*Hint:* In earlier guideline versions, we used the `Warning` header to provide
the deprecation info (see hint in <<189>>).

[#191]
== {MUST} not start using deprecated APIs

Clients must not start using deprecated APIs or deprecated parts of an API.
