[[deprecation]]
= Deprecation

Sometimes it is necessary to phase out an API endpoint (or version), for
instance, if a field is no longer supported in the result or a whole business
functionality behind an endpoint has to be shut down. There are many other
reasons as well. As long as these endpoints are still used by consumers these
are breaking changes and not allowed. Deprecation rules have to be applied to
make sure that necessary consumer changes are aligned and deprecated endpoints
are not used before API changes are deployed. 


[#185]
== {MUST} obtain approval of clients

Before shutting down an API (or version of an API) the producer must
make sure, that all clients have given their consent to shut down the
endpoint. Producers should help consumers to migrate to a potential new
endpoint (i.e. by providing a migration manual). After all clients are
migrated, the producer may shut down the deprecated API.


[#186]
== {MUST} external partners must agree on deprecation time span

If the API is consumed by any external partner, the producer must define
a reasonable time span that the API will be maintained after the producer
has announced deprecation. The external partner (client) must agree to
this minimum after-deprecation-life-span before he starts using the API.


[#187]
== {MUST} reflect deprecation in API specifications

API deprecation must be part of the Open API definition. 
If an API endpoint (operation object), an input argument (parameter object), 
or in/out data object (schema object) should be deprecated, the producers 
must set `deprecated: true` for the element. 
If deprecation should happen on a more fine grained level (i.e. schema attribute etc.), 
the producer should set `deprecated: true` on the affected element and add further
explanation to the `description` section.

If `deprecated` is set to `true`, the producer must provide a sunset date and 
describe what consumers should use instead (possibly via links to details) 
in the `description` section.


[#188]
== {MUST} monitor usage of deprecated APIs and API endpoints

Owners of APIs used in production must monitor usage of deprecated APIs
until the API can be shut down in order to align deprecation and avoid
uncontrolled breaking effects. See also the <<193>>.


[#189]
== {SHOULD} add a deprecation header to responses

During deprecation phase, the producer should add a `Deprecation` header 
(see
https://tools.ietf.org/html/draft-dalal-deprecation-header[draft: RFC Deprecation HTTP Header])
with the sunset date value (in {RFC-7231}#section-7.1.1.1[HTTP Date/Time] form): 

[source,txt]
----
Deprecation: Sun, 11 Nov 2018 23:59:59 GMT
----

Note, adding the `Deprecation` header is not sufficient to gain client consent to shut down an API.

*Hint:* In earlier guideline versions, we used the `Warning` header to provide the deprecation info to clients. 
However, `Warning` header has less specific semantics, will be obsolete with 
https://tools.ietf.org/html/draft-ietf-httpbis-cache-06[draft: RFC HTTP Caching], 
and our syntax was not conform with {RFC-7234}#page-29[RFC 7234 -- Warning header].


[#190]
== {SHOULD} add monitoring for deprecation header

Clients should monitor the `Deprecation` header in HTTP responses to get information about future sunset of API features. 

*Hint:* In earlier guideline versions, we used the `Warning` header to provide the deprecation info -- see hint in <<189>>.

[#191]
== {MUST} not start using deprecated APIs

Clients must not start using deprecated parts of an API.
