[[appendix-standard-style]]
[appendix]
= Pon Standard Style

Pon standard style can be applied when linters are not available.

Based on <<standardJs>>, <<googleStyleguideJs>>, <<phpStandards>>


[#253]
== {MUST} use special quotes only to reduce complexity

In most programming languages several options are available for the quoting of
text, in the following examples Javascript style quoting is used which is
applicable to a variety of other programming languages.

For the following examples the key question is: can the readbility be improved
to make the code more simple and concise?

=== Example 1

[source,javascript]
----
text = "The quick brown fox jumped over the lazy dog"
----

Although the code is correct the double quotes have have no additional function,
the following code is more concise by using single quotes:

[source,javascript]
----
text = 'The quick brown fox jumped over the lazy dog'
----

=== Example 2

[source,javascript]
----
text = "The quick brown \"fox\" jumped over the lazy dog"
----

The code is correct, but readability is improved by switching to single quotes:

[source,javascript]
----
text = 'The quick brown "fox" jumped over the lazy dog'
----

=== Languages

{LANG-JAVASCRIPT-ICON} {LANG-TYPESCRIPT-ICON} {LANG-PHP-ICON}

=== References

* <<googleStyleguideJs>>, link:https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes[Use single quotes]
* <<standardJs>>, Use single quotes for strings 
* <<development-rules-definitions>>, <<244>>
* <<development-rules-definitions>>, <<254>>

[#257]
== {MUST} never use tabs for indentation

Tabs are never to be used for indentation.

=== Languages

{LANG-ALL-ICON}

=== References

* <<googleStyleguideJs>>, link:https://google.github.io/styleguide/jsguide.html#whitespace-characters[whitespace characters (2)]
* <<standardJs>>, Tabs should not be used
* <<phpStandards>>, link:https://www.php-fig.org/psr/psr-12/#24-indenting[indenting]
* <<development-rules-definitions>>, <<244>>
* <<development-rules-definitions>>, <<254>>


[#251]
== {MUST} use predefined spacing for indentation 

Using predefined spacing for indentation results in clear readable code without
sacrificing too much screen real estate; <<257>>.

When using multiple languages a single project it is perferred to use the same
indent for all languagues involved.

=== Languages

==== {MUST} Spacing: 2
{LANG-JAVASCRIPT-ICON} {LANG-TYPESCRIPT-ICON} 

==== {SHOULD} Spacing: 2
{LANG-PHP-ICON}

==== {MAY} Spacing: 4
{LANG-PHP-ICON}

=== References

* <<googleStyleguideJs>>, link:https://google.github.io/styleguide/jsguide.html#whitespace-characters[whitespace characters (2)]
* <<standardJs>>, Use 2 spaces for indentation
* <<phpStandards>>, link:https://www.php-fig.org/psr/psr-12/#24-indenting[indenting]
* <<development-rules-definitions>>, <<244>>


[#256]
== {MUST} not have unused variables

All variables are in use, unused variables have no function and are cluttering
the code.

=== Languages

{LANG-ALL-ICON}

=== References

* <<standardJs>>, No unused variables
* <<development-rules-definitions>>, <<244>>






[[references]]
== References

- [[standardJs]] standardJS https://standardjs.com/index.html
- [[googleStyleguideJs]] Google Javascript styleguide https://google.github.io/styleguide/jsguide.html
- [[phpStandards]] PHP Standards Recommendations https://www.php-fig.org/psr/




