[[appendix-standard-style]]
[appendix]
= Pon Standard Style

Pon standard style can be applied when linters are not available.

Based on <<standardJs>>, <<googleStyleguideJs>>


[#253]
== {SHOULD} use special quotes only to reduce complexity

In most programming languages several options are available for the quoting of
text, in the following examples Javascript style quoting is used which is
applicable to a variety of other programming languages.

For the following examples the key question is: can the readbility be improved
to make the code more simple and concise?

=== Example 1

`text = "The quick brown fox jumped over the lazy dog"`

Although the code is correct the double quotes have have no additional function,
the following code is more concise by using single quotes:

`text = 'The quick brown fox jumped over the lazy dog'`

=== Example 2

`text = "The quick brown \"fox\" jumped over the lazy dog"`

The code is correct, but readability is improved by switching to single quotes:

`text = 'The quick brown "fox" jumped over the lazy dog'`

[small]#Based on rule(s): <<254, code is simple and concise>>#

=== References

* <<googleStyleguideJs>> link:https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes[Use single quotes]
* <<standardJs>> Use single quotes for strings 

[#251]
== {MUST} use two spaces for indentation 

Using two spaces for indentation results in clear readable code without
sacrificing too much screen real estate. Tabs are never to be used.

[small]#Based on rule(s): <<244, logical structured code>>#

=== Languages

[%autowidth]
[frame=none]
|===
| {LANG-JAVASCRIPT-ICON} | {LANG-PHP-ICON}
|===

=== References

* <<googleStyleguidJs>> link:https://google.github.io/styleguide/jsguide.html#whitespace-characters[Whitespace characters (2)]
* <<standardJs>> Use 2 spaces for indentation

[[references]]
== References

- [[standardJs]] standardJS https://standardjs.com/index.html
- [[googleStyleguideJs]] Google Javascript styleguide https://google.github.io/styleguide/jsguide.html



