[[general-guidelines]]
= General Guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.

[#100]
== {MUST} Follow API First Principle

* You must define APIs outside the code first <<101, using OpenAPI as specification language>>
* You must call for early review feedback from peers and client developers, 
and apply our https://github.bus.zalan.do/ApiGuild/ApiReviewProcedure[lightweight API
review process [internal link]] for all <<219, component external APIs>> 


[#101]
== {MUST} Provide API Specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] (aka
Swagger specification) as standard to define API specifications files.
API designers have to provide the API specification files using *YAML*
to improve readability. Please, use *OpenAPI 2.0* for now, until we 
have updated all our tooling to support new OpenAPI 3.0 version. 

The API specifications must be provided with <<218, Metadata>> 
and <<219, component external APIs>> (at least) <<192, must be published>>
as to be discoverable by the group via our https://apis.zalando.net/[API Portal [internal link]].

The https://github.com/zalando/zally[Zalando API Linter Zally]
should be used to design APIs compliant with this API guideline. 

The API specification files should be subject to version control using
a source code management system - best together with the implementing sources. 


[#102]
== {SHOULD} Provide API User Manual

In addition to the API Specification, it is good practice to provide an
API user manual to improve client developer experience, especially of
engineers that are less experienced in using this API. A helpful API user
manual typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via GHE pages, on specific
team web servers, or as a Google doc. Please do not forget to include a
link to the API user manual into the API specification using the
`#/externalDocs/url` property.

[#103]
== {MUST} Write APIs in U.S. English

