[[general-guidelines]]
= General Guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.

[#100]
== {MUST} Follow API First Principle

You must follow the <<api-first, API First Principle>>, more specifically: 

* You must define APIs first, before coding its implementation, <<101, using OpenAPI as specification language>>
* You must call for early review feedback from peers and client developers, 
and apply https://github.bus.zalan.do/ApiGuild/ApiReviewProcedure[our lightweight API
review process [internal link]] for all component external APIs, i.e. 
all apis with `x-api-audience =/= component-internal` (see <<219, API Audience>>). 


[#101]
== {MUST} Provide API Specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] as standard
to define API specification files. API designers are required to provide the API
specification using a single *self-contained YAML* file to improve readability.
We encourage to use *OpenAPI 3.0* version, but still support *OpenAPI 2.0*
(a.k.a. Swagger 2).

The API specification files should be subject to version control using a source
code management system - best together with the implementing sources. 

You <<192, must / should publish>> the component <<219, external / internal>>
API specification with the deployment of the implementing service, and, hence,
make it discoverable for the group via our https://apis.valimail.com/[API Portal
[internal link]].

*Hint:* A good way to explore *OpenAPI 3.0/2.0* is to navigate through the
https://openapi-map.apihandyman.io/[OpenAPI specification mind map] and use
our https://plugins.jetbrains.com/search?search=swagger+Monte[Swagger Plugin
for IntelliJ IDEA] to create your first API. To explore and validate/evaluate
existing APIs the https://editor.swagger.io/[Swagger Editor] or our
https://apis.valimail.com[API Portal] may be a good starting point.


[#234]
== {MUST} only use Durable and Immutable Remote References

Normally, API specification files must be *self-contained*, i.e. files
should not contain references to local or remote content, e.g. `../fragment.yaml#/element` or
TODO: dewayne.richardson
Setup link to Valimail swagger refs
The reason is, that the content referred to is _in general_ *not durable* and
*not immutable*. As a consequence, the semantic of an API may change in
unexpected ways.

However, you may use remote references to resources accessible by the following
service URLs.

TODO: dewayne.richardson - refer example at valimail repos

As we control these URLs, we ensure that their content is *durable* and
*immutable*. This allows to define API specifications by using fragments
published via this sources, as suggested in <<151>>.


[#102]
== {SHOULD} Provide API User Manual

In addition to the API Specification, it is good practice to provide an API
user manual to improve client developer experience, especially of engineers
that are less experienced in using this API. A helpful API user manual
typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via our documentation hosting
platform service, GHE pages, or specific team web servers. Please do not forget
to include a link to the API user manual into the API specification using the
`#/externalDocs/url` property.


[#103]
== {MUST} Write APIs in U.S. English

