[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.


[#100]
== {MUST} follow API first principle

You must follow the <<api-first, API First Principle>>, more specifically:

* You must define APIs first, before coding its implementation, <<101, using
  OpenAPI as specification language>>
* You must design your APIs consistently with these guidelines
* You must call for early review feedback from peers and client developers


[#101]
== {MUST} provide API specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] as standard
to define API specification files. API designers are required to provide the API
specification using a single *self-contained YAML* file to improve readability.
We support OpenAPI starting from *OpenAPI 3.0* version only.

The API specification files should be subject to version control using a source
code management system - best together with the implementing sources.

[#102]
== {MUST} publish API specification to SwaggerHub

All of our APIs are published to https://app.swaggerhub.com/home?type=API&owner=hypatos.ai[SwaggerHub].

[#103]
== {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide an API
user manual to improve client developer experience, especially of engineers
that are less experienced in using this API. A helpful API user manual
typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via our documentation hosting
platform service, GHE pages, or specific team web servers. Please do not forget
to include a link to the API user manual into the API specification using the
`#/externalDocs/url` property.


[#104]
== {MUST} write APIs using U.S. English
