[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.


[#100]
== {MUST} follow API first principle

You must follow the <<api-first, API First Principle>>, more specifically:

* You must define APIs first, before coding its implementation, <<101, using
  OpenAPI as specification language>>
* You must design your APIs consistently with these guidelines; 
  {TODO}: Linter process for automated rule checks.


[#101]
== {MUST} provide API specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] as standard
to define API specification files. API designers are required to provide the API
specification using a single *self-contained YAML* file to improve readability.
We encourage to use *OpenAPI 3.0* version.

The API specification files should be subject to version control using a source
code management system - best together with the implementing sources.

You <<192, must / should publish>> the component <<219, external / internal>>
API specification with the deployment of the implementing service, and, hence,
make it discoverable for the group via our {api-portal}[API Portal (internal_link)]. {TODO}

*Hint:* We do not yet provide guidelines for https://graphql.org/[GraphQL]
and focus on resource oriented HTTP/REST API style (and related tooling 
and infrastructure support).


[#102]
== {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide an API
user manual to improve client developer experience, especially of engineers
that are less experienced in using this API. A helpful API user manual
typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via our documentation hosting
platform service, GHE pages, or specific team web servers. Please do not forget
to include a link to the API user manual into the API specification using the
`#/externalDocs/url` property.


[#103]
== {MUST} write APIs using U.S. English


[#234]
== {MUST} only use durable and immutable remote references

Normally, API specification files must be *self-contained*, i.e. files
should not contain references to local or remote content.
The reason is, that the content referred to is _in general_ *not durable* and
*not immutable*. As a consequence, the semantic of an API may change in
unexpected ways. (For example, the second link is already outdated due to code restructuring.)

As we control these URLs, we ensure that their content is *durable* and
*immutable*. This allows to define API specifications by using fragments
published via these sources, as suggested in <<151>>. {TODO}
