[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.


[#100]
== {STATUS-RFP} {MUST} follow API first principle

You must follow the <<api-first, API First Principle>>, more specifically: 

* You must define APIs first, before coding its implementation.
* You must call for review feedback from peers and client developers. 


[#101]
== {STATUS-RFP} {MUST} provide API specification

Must provide API specification according to standards as specified for API platform.

The API specification files should be subject to version control using a source
code management system - best together with the implementing sources. 

You <<192, must / should publish>> the component <<219, external / internal>>
API specification with the deployment of the implementing service, and, hence,
make it discoverable.


[#234]
== {STATUS-RFP} {MUST} only use durable and immutable remote references

Normally, API specification files must be *self-contained*, i.e. files
should not contain references to local or remote content, e.g. `../fragment.yaml#/element` or
`$ref: 'https://github.com/zalando/zally/blob/master/server/src/main/resources/api/zally-api.yaml#/schemas/LintingRequest'`.


[#102]
== {STATUS-RFP} {MAY} provide API user manual

In addition to the API Specification, it is good practice to provide an API
user manual to improve client developer experience, especially of engineers
that are less experienced in using this API. A helpful API user manual
typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via our documentation hosting
platform service, GHE pages, or specific team web servers. Please do not forget
to include a link to the API user manual into the API specification using the
`#/externalDocs/url` property.


[#103]
== {STATUS-RFP} {MUST} write APIs using U.S. English
