[[general-guidelines]]
= General Guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.

[#100]
== {MUST} Follow API First Principle

* You must define APIs outside the code first <<101, using OpenAPI as definition language>>
* You must call for early review feedback from peers and client developers, 
and apply our https://github.bus.zalan.do/ApiGuild/ApiReviewProcedure[lightweight API
review process [internal link]] for all <<192, component external APIs>> 


[#101]
== {MUST} Provide API Specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] (aka
Swagger specification) as standard to define API specifications files.
API designers have to provide the API specification files using *YAML*
to improve readability.

Please stick to OpenAPI 2.0 for now, until we succeed to update all our
tooling to support the upcoming OpenAPI 3.0.0.

The API specification files should be subject to version control using
a source code management system - best together with the implementing
sources. The API specifications of component external APIs <<192, must
be published>> and <<219, marked with the intended target audience>>.

The https://github.com/zalando/zally[Zalando API Linter Zally]
should be used to design APIs compliant with this API guideline. Please
have also a look to the
https://pages.github.bus.zalan.do/ApiGuild/ApiReviewProcedure/[API review
procedures [internal link]].


[#102]
== {SHOULD} Provide API User Manual

In addition to the API Specification, it is good practice to provide an
API user manual to improve client developer experience, especially of
engineers that are less experienced in using this API. A helpful API user
manual typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via GHE pages, on specific
team web servers, or as a Google doc. Please do not forget to include a
link to the API user manual into the API specification using the
`#/externalDocs/url` property.

[#103]
== {MUST} Write APIs in U.S. English

