[[http-status-codes-and-errors]]
= REST Basics - HTTP status codes


[#243]
== {MUST} use official HTTP status codes

You must only use official HTTP status codes consistently with their intended
semantics. Official HTTP status codes are defined via RFC standards and
registered in the
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml[IANA
Status Code Registry]. Main RFC standards are {RFC-7231}#section-6[RFC7231 -
HTTP/1.1: Semantics] (or {RFC-7235}#page-6[RFC7235 - HTTP/1.1: Authentication])
and {RFC-6585}[RFC 6585 - HTTP: Additional Status Codes] (and there are
upcoming new ones, e.g.
https://tools.ietf.org/html/draft-tbray-http-legally-restricted-status-05[draft
legally-restricted-status]). An overview on the official error codes provides
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[Wikipedia: HTTP status
codes] (which also lists some unofficial status codes, e.g. defined by popular
web servers like Nginx, that we do not suggest to use).


[#151]
== {MUST} specify success and error responses

APIs should define the functional, business view and abstract from
implementation aspects. Success and error responses are a vital part to
define how an API is used correctly.

Therefore, you must define **all** success and service specific error responses
in your API specification. Both are part of the interface definition and
provide important information for service clients to handle standard as well as
exceptional situations. Error code response descriptions should provide
information about the specific conditions that lead to the error, especially if
these conditions can be changed by how the endpoint is used by the clients.

API designers should also think about a **troubleshooting board** as part of
the associated online API documentation. It provides information and handling
guidance on application-specific errors and is referenced via links from the
API specification. This can reduce service support tasks and contribute to
service client and provider performance.

**Exception:** Standard client and server errors, e.g. {401} (unauthenticated),
{403} (unauthorized), {404} (not found), {500} (internal server error), or
{503} (service unavailable), where the semantic can be easily derived from the
end endpoint specification need no individual definition. Instead these can be
included by applying the {TODO} `default` shown pattern below. However, error codes
that provide endpoint specific indications for clients on how to avoid calling
the endpoint in the wrong way, or be prepared to react on specific error
situation must be specified explicitly.

[source,yaml]
----
responses:
  ...
  default:
    description: error occurred - see status code and problem object for more information.
    content:
      "application/problem+json":
        schema:
          $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.1.yaml#/Problem'
----


[#150]
== {MUST} only use most common HTTP status codes

The most commonly used codes are best understood and listed below as subset of
the official HTTP status codes and consistent with their semantics in the RFCs.
We avoid less commonly used codes that easily create misconceptions due to
less familiar semantics and API specific interpretations.

**Important:** As long as your HTTP status code usage is well covered by the
semantic defined here, you should not describe it to avoid an overload with
common sense information and the risk of inconsistent definitions. Only if the
HTTP status code is not in the list below or its usage requires additional
information aside the well defined semantic, the API specification must provide
a clear description of the HTTP status code in the response.

[[status-code-legend]]
=== Legend

A more specific version of the <<conventions-used-in-these-guidelines>>.

[[status-code-use]]
==== {use}
A common, well understood status code that should be used where appropriate.
Does NOT mean that every operation must be able to return this code.

[[status-code-do-not-use]]
==== {do-not-use}
We do not see a good use-case for returning this status code from a RESTful
API. The status code might be applicable in other contexts, e.g. returned by
reverse proxies, for web pages, etc. Implicitly also means {do-not-document},
as status codes that are not returned by the API should also not be documented.

[[status-code-document]]
==== {document}
If the status code can be returned by the API, it should be documented in the
API specification.

[[status-code-do-not-document]]
==== {do-not-document}
The status code has a well-understood standard meaning to it, so only document
it if there are operation specific details you want to add. See exception in
<<151, rule 151>>.


[[success-codes]]
=== Success codes

[[status-code-200]]
==== 200 OK {rfc-status-200} {use} {document} {ALL}
[.indent]
This is the most general success response. It should be used if the more
specific codes below are not applicable. In a robust resource creation via
{POST}, {PUT}, and {PATCH} in conjunction with a {201} this indicates that the
returned resource exists before.

[[status-code-201]]
==== 201 Created {rfc-status-201} {use} {document} {POST} {PUT}
[.indent]
Returned on successful resource creation.
{201} is returned with or without response payload (unlike {200} / {204}).
We recommend additionally to return the created resource URL via the {Location}
response header (see <<133>>).


[[status-code-202]]
==== 202 Accepted {rfc-status-202} {use} {document} {POST} {PUT} {PATCH} {DELETE}
[.indent]
The request was successful and will be processed asynchronously.
Only applicable to methods which change something, with the exception of
{GET} methods indicating that a resources is still created asynchronously
as described in <<253>>.

[[status-code-204]]
==== 204 No content {rfc-status-204} {use} {document} {POST} {PUT} {PATCH} {DELETE}
[.indent]
Returned instead of {200}, if no response payload is returned. Normally only
applicable to methods which change something.


[[client-side-error-codes]]
=== Client side error codes

[[status-code-400]]
==== 400 Bad Request {rfc-status-400} {use} {document} {ALL}
[.indent]
Unspecific client error indicating that the server cannot process the request
due to something that is perceived to be a client error (e.g. malformed request
syntax, invalid request). Should also be delivered in case of input payload
fails business logic / semantic validation (instead of using {422}).

[[status-code-401]]
==== 401 Unauthorized {rfc-status-401} {use} {do-not-document} {ALL}
[.indent]
Actually *Unauthenticated*. The credentials are missing or not valid for the
target resource. For an API, this usually means that the provided token or
cookie is not valid. As this can happen for almost every endpoint, APIs should
normally not document this.

[[status-code-403]]
==== 403 Forbidden {rfc-status-403} {do-not-document} {ALL}
[.indent]
The user is not authorized to use this resource. For an API, this can mean that
the request's token was valid, but was missing a scope for this endpoint. Or
that some object-specific authorization failed. We recommend only documenting
the second case.

[[status-code-404]]
==== 404 Not found {rfc-status-404} {use} {do-not-document} {ALL}
[.indent]
The target resource was not found. This will be returned by most paths on most
APIs (with out being documented), and for endpoints with parameters when those
parameters cannot be map to an existing entity. For a {PUT} endpoint which only
supports updating existing resources, this might be returned if the resource
does not exist. Apart from these special cases, this does not need to be
documented.

=== Server side error codes

[[status-code-500]]
==== 500 Internal Server Error {rfc-status-500} {use} {do-not-document} {ALL}
[.indent]
A generic error indication for an unexpected server execution problem. Clients
should be careful with retrying on this response, since the nature of the
problem is unknown and must be expected to continue.


[#220]
== {MUST} use most specific HTTP status codes

You must use the most specific HTTP status code when returning information
about your request processing status or error situations.

[#176]
== {MUST} support problem JSON

{RFC-9457}[RFC 9457] defines a Problem JSON object using the media type
`application/problem+json` to provide an extensible human and machine readable
failure information beyond the HTTP response status code to transports the
failure kind (`type` / `title`) and the failure cause and location (`instant` /
`detail`). To make best use of this additional failure information, every
endpoints must be capable of returning a Problem JSON on client usage errors
({4xx} status codes) as well as server side processing errors ({5xx} status
codes).

*Note:* Clients must be robust and *not rely* on a Problem JSON object
being returned, since (a) failure responses may be created by infrastructure
components not aware of this guideline or (b) service may be unable to comply
with this guideline in certain error situations.

*Hint:* The media type `application/problem+json` is often not implemented as
a subset of `application/json` by libraries and services! Thus clients need to
include `application/problem+json` in the {Accept}-Header to trigger delivery
of the extended failure information.

The OpenAPI schema definition of the Problem JSON object can be found
https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.1.yaml[on
GitHub]. You can reference it by using:

[source,yaml]
----
responses:
  503:
    description: Service Unavailable
    content:
      "application/problem+json":
        schema:
          $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.1.yaml#/Problem'
----

You may define custom problem types as extensions of the Problem JSON object
if your API needs to return specific, additional, and more detailed error
information.

*Note:* Problem `type` and `instance` identifiers in our APIs are not meant
to be resolved. {RFC-9457}[RFC 9457] encourages that problem types are URI
references that point to human-readable documentation, *but* we deliberately
decided against that, as all important parts of the API must be documented
using <<101, OpenAPI>> anyway. In addition, URLs tend to be fragile and not
very stable over longer periods because of organizational and documentation
changes and descriptions might easily get out of sync.

In order to stay compatible with {RFC-9457}[RFC 9457] we proposed to use
https://tools.ietf.org/html/rfc3986#section-4.1[relative URI references]
usually defined by `absolute-path [ '?' query ] [ '#' fragment ]` as simplified
identifiers in `type` and `instance` fields:

* `/problems/out-of-stock`
* `/problems/insufficient-funds`
* `/problems/user-deactivated`
* `/problems/connection-error#read-timeout`

*Hint:* The use of https://tools.ietf.org/html/rfc3986#section-4.3[absolute
URIs] is not forbidden but strongly discouraged. If you use absolute URIs,
please reference
https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.0.yaml#/Problem[problem-1.0.0.yaml#/Problem]
instead.


[#177]
== {MUST} not expose stack traces

Stack traces contain implementation details that are not part of an API,
and on which clients should never rely. Moreover, stack traces can leak
sensitive information that partners and third parties are not allowed to
receive and may disclose insights about vulnerabilities to attackers.
