[[headers]]
= REST Basics - HTTP headers

[[standard-headers]]
// hint: legacy anchor positioned here
// acsciidoc does not support two anchors in sequence

In this section we explain a handful of (standard) HTTP headers, which we found
most useful in certain situations and that require additional explanation to be
used effectively.

*Note:* we generally discourage the usage of proprietary headers. However,
they are sometimes useful to pass generic, service independent, overarching
information relevant for our specific application architecture. We consistently
define these proprietary headers below.

Whether a service supports a certain header is part of the service contract.
Therefore APIs should use the `parameters` and `headers` definition of the API
endpoint and response to clarify what is supported in a certain context.

[[using-headers]]
== Using Standard Header definitions

Usually, you can the standard HTTP request and response header definition
provided by the guideline to simplify API by using well recognized patterns.
The best practice importing headers providing the highest readability is as
follows:

[source,yaml]
----
path:
  '/resource'
    get:
      parameters:
        - $ref: '#/components/parameters/ETag

components:
  parameters|headers:
    ETag:
      $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/headers-1.0.0.yaml#/ETag'

  responses:
    Default:
      headers:
        ETag:
          $ref: '#/components/(parameters|headers)/ETag'
----

*Note:* It is a question of taste whether headers for responses are defined in
`\#/components/headers` or `#/components/parameters`. Unfortunately, headers
in the first section cannot be referenced from a `parameters`-list, while it is
possible to reference the second also from a `headers`-list.


[#133]
== {MUST} use standard headers

APIs may make use of HTTP headers defined by non-obsolete RFCs (see following
list of http://en.wikipedia.org/wiki/List_of_HTTP_header_fields[standard HTTP
headers]). The supported headers must be explicitly mentioned in the API
specification.

*Exception*: `X-API-Key` header
