[[introduction]]
= Introduction

10M is not a microservice company. But developing client/server
archictures with independent frontend and backend teams require
stable API architectures. Out estabilished standard for public APIs
that provide functionality via RESTful APIs with a JSON payload. Our
engineering teams own, deploy and operate these services in their
AWS (team) accounts. Our APIs most purely express what our systems do,
and are therefore highly valuable business assets. 

With this in mind, we’ve adopted "API First" as one of our key
engineering principles. Microservices development begins with API
definition outside the code and ideally involves ample peer-review
feedback to achieve high-quality APIs. API First encompasses a set of
quality-related standards and fosters a peer review culture including a
lightweight review procedure. We encourage our teams to follow them to
ensure that our APIs:

* are easy to understand and learn
* are general and abstracted from specific implementation and use cases
* are robust and easy to use
* have a common look and feel
* follow a consistent RESTful style and syntax
* are consistent with other teams’ APIs and our global architecture

Ideally, all our APIs will look like the same author created them.

[[conventions-used-in-these-guidelines]]
== Conventions Used in These Guidelines

The requirement level keywords "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" used in this document (case insensitive) are to be
interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC
2119].


In case guidelines are changing, following rules apply:

* existing APIs don't have to be changed, but we recommend it
* clients of existing APIs have to cope with these APIs based on
outdated rules
* new APIs have to respect the current guidelines

Furthermore you should keep in mind that once an API becomes public
externally available, it has to be re-reviewed and changed according to
current guidelines - for sake of overall consistency.

