[[introduction]]
= Introduction

NUPANO’s software architecture centers around decoupled microservices
that provide functionality via RESTful APIs with a JSON payload.
Our strategy emphasizes developing lots of public APIs for our
external business partners to use via third-party applications.

With this in mind, we’ve adopted "API First" as one of our key
engineering principles. Microservices development begins with API
definition outside the code and ideally involves ample peer-review
feedback to achieve high-quality APIs. API First encompasses a set of
quality-related standards and fosters a peer review culture including a
lightweight review procedure. We encourage our teams to follow them to
ensure that our APIs:

* are easy to understand and learn
* are general and abstracted from specific implementation and use cases
* are robust and easy to use
* have a common look and feel
* follow a consistent RESTful style and syntax
* are consistent with other teams’ APIs and our global architecture

Ideally, all NUPANO APIs will look like the same author created them.


[[conventions-used-in-these-guidelines]]
== Conventions used in these guidelines

The requirement level keywords "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" used in this document (case insensitive) are to be
interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC
2119].
