[[introduction]]
= Introduction

Pon's software architecture centers around decoupled microservices that provide
functionality via APIs. Small engineering teams own, deploy and operate these
microservices. Our APIs most purely express what our systems do, and are
therefore highly valuable business assets.

With this in mind, we’ve adopted "API First" as one of our key engineering
principles. Microservices development begins with API definition outside the
code and ideally involves ample peer-review feedback to achieve high-quality
APIs. API First encompasses a set of quality-related standards and fosters a
peer review culture including a lightweight review procedure. We encourage our
teams to follow them to ensure that our APIs:

* are easy to understand and learn 
* are general and abstracted from specific implementation and use cases 
* are robust and easy to use 
* have a common look and feel 
* follow a consistent RESTful style and syntax 
* are consistent with other teams’ APIs and our global architecture

Ideally, all Pon APIs will look like the same author created them.

== Attribution

These guidelines are based on the link:https://github.com/zalando/restful-api-guidelines[Zalando restful api guidelines].

[[conventions-used-in-these-guidelines]]
== Conventions used in these guidelines

The requirement level keywords "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" used in this document (case insensitive) are to be
interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC
2119].


[[pon-specific-information]]
== Pon specific information

The purpose of these guidelines is to define standards to successfully establish
"consistent integration and development look and feel" quality. The integration
guild drafted and owns this document. Teams are responsible to fulfill these
guidelines during API development and are encouraged to contribute to guideline
evolution via pull requests.

These guidelines will, to some extent, remain work in progress as our work
evolves, but teams can confidently follow and trust them.

In case guidelines are changing, the following rules apply:

* existing APIs don't have to be changed, but we recommend it 
* clients of existing APIs have to cope with these APIs based on outdated rules 
* new APIs have to respect the current guidelines

Furthermore you should keep in mind that once an API becomes public externally
available, it has to be re-reviewed and changed according to current guidelines
- for the sake of overall consistency.

