[[json-guidelines]]
= REST - JSON payload

These guidelines provides recommendations for defining JSON data at Zalando.
JSON here refers to {RFC-7159}[RFC 7159] (which updates {RFC-4627}[RFC 4627]),
the "application/json" media type and custom JSON media types defined for APIs.
The guidelines clarifies some specific cases to allow Zalando JSON data to have
an idiomatic form across teams and services.

The first some of the following guidelines are about property names, the later
ones about values.


[#120]
== {SHOULD} pluralize array names

Names of arrays should be pluralized to indicate that they contain multiple values.
This implies in turn that object names should be singular.


[#118]
== {MUST} property names must be snake_case (and never camelCase)

Property names are restricted to ASCII snake_case strings matching regex `^[a-z_][a-z_0-9]*$`. 
The first character must be a lower case letter, or an underscore, and subsequent
characters can be a letter, an underscore, or a number.

Examples:

[source]
----
customer_number, sales_order_number, billing_address
----

Rationale: No established industry standard exists, but many popular Internet
companies prefer snake_case: e.g. GitHub, Stack Exchange, Twitter.
Others, like Google and Amazon, use both - but not only camelCase. It’s
essential to establish a consistent look and feel such that JSON looks
as if it came from the same hand.

[#125]
[#240]
== {SHOULD} declare enum values using UPPER_SNAKE_CASE string 

Enumerations should be represented as `string` typed OpenAPI definitions of 
request parameters or model properties.
Enum values (using `enum` or {x-extensible-enum}) need to consistently use 
the upper-snake case format, e.g. `VALUE` or `YET_ANOTHER_VALUE`. 
This approach allows to clearly distinguish values from properties or other elements.

**Exception:** This rule does not apply for case sensitive values sourced from outside 
API definition scope, e.g. for language codes from {ISO-639-1}[ISO 639-1], or when 
declaring possible values for a <<137,rule 137>> [`sort` parameter].

[#216]
== {SHOULD} define maps using `additionalProperties`

A "map" here is a mapping from string keys to some other type. In JSON this is
represented as an object, the key-value pairs being represented by property
names and property values. In OpenAPI schema (as well as in JSON schema) they
should be represented using additionalProperties with a schema defining the
value type. Such an object should normally have no other defined properties.

The map keys don't count as property names in the sense of <<118,rule 118>>,
and can follow whatever format is natural for their domain. Please document
this in the description of the map object's schema.

Here is an example for such a map definition (the `translations` property):

```yaml
components:
  schemas:
    Message:
      description:
        A message together with translations in several languages.
      type: object
      properties:
        message_key:
          type: string
          description: The message key.
        translations:
          description:
            The translations of this message into several languages.
            The keys are [IETF BCP-47 language tags](https://tools.ietf.org/html/bcp47).
          type: object
          additionalProperties:
            type: string
            description:
              the translation of this message into the language identified by the key.
```

An actual JSON object described by this might then look like this:
```json
{ "message_key": "color",
  "translations": {
    "de": "Farbe",
    "en-US": "color",
    "en-GB": "colour",
    "eo": "koloro",
    "nl": "kleur"
  }
}
```


[#122]
== {MUST} not use `null` for boolean properties

Schema based JSON properties that are by design booleans must not be
presented as nulls. A boolean is essentially a closed enumeration of two
values, true and false. If the content has a meaningful null value,
strongly prefer to replace the boolean with enumeration of named values
or statuses - for example accepted_terms_and_conditions with true or
false can be replaced with terms_and_conditions with values yes, no and
unknown.


[#123]
== {MUST} use same semantics for `null` and absent properties

OpenAPI 3.x allows to mark properties as `required` and as `nullable` to
specify whether properties may be absent (`{}`) or `null` (`{"example":null}`).
If a property is defined to be not `required` and `nullable` (see
<<required-nullable-row-2, 2nd row in Table below>>), this rule demands
that both cases must be handled in the exact same manner by specification.

The following table shows all combinations and whether the examples are
valid:

[cols=",,,",options="header",]
|===========================================
| {CODE-START}required{CODE-END} | {CODE-START}nullable{CODE-END}
| {CODE-START}{}{CODE-END} | {CODE-START}{"example":null}{CODE-END}
| `true`  |`true`   | {NO}  | {YES}
| `false` | `true`  | {YES} | {YES} [[required-nullable-row-2]]
| `true`  |`false`  | {NO}  | {NO}
| `false` |`false`  | {YES} | {NO}
|===========================================

While API designers and implementers may be tempted to assign different
semantics to both cases, we explicitly decide **against** that option, because we
think that any gain in expressiveness is far outweighed by the risk of clients
not understanding and implementing the subtle differences incorrectly.

As an example, an API that provides the ability for different users to
coordinate on a time schedule, e.g. a meeting, may have a resource for options
in which every user has to make a `choice`. The difference between _undecided_
and _decided against any of the options_ could be modeled as _absent_ and
`null` respectively. It would be safer to express the `null` case with a
dedicated https://en.wikipedia.org/wiki/Null_object_pattern[Null object], e.g.
`{}` compared to `{"id":"42"}`.

Moreover, many major libraries have somewhere between little to no support for
a `null`/absent pattern (see
https://stackoverflow.com/questions/48465005/gson-distinguish-null-value-field-and-missing-field[Gson],
https://github.com/square/moshi#borrows-from-gson[Moshi],
https://github.com/FasterXML/jackson-databind/issues/578[Jackson],
https://developer.ibm.com/articles/j-javaee8-json-binding-3/[JSON-B]). Especially
strongly-typed languages suffer from this since a new composite type is required
to express the third state. Nullable `Option`/`Optional`/`Maybe` types could be
used but having nullable references of these types completely contradicts their
purpose.

The only exception to this rule is JSON Merge Patch {RFC-7396}[RFC 7396]) which
uses `null` to explicitly indicate property deletion while absent properties are
ignored, i.e. not modified.


[#124]
== {SHOULD} not use `null` for empty arrays

Empty array values can unambiguously be represented as the empty list, `[]`.


[#235]
== {SHOULD} name date/time properties with `_at` suffix

Dates and date-time properties should end with `_at` to distinguish them from
boolean properties which otherwise would have very similar or even identical
names:

- {created_at} rather than {created},
- {modified_at} rather than {modified},
- `occurred_at` rather than `occurred`, and
- `returned_at` rather than `returned`.

**Note:** {created} and {modified} were mentioned in an earlier version of the
guideline and are therefore still accepted for APIs that predate this rule.


[[common-data-types]]
Definitions of data objects that are good candidates for wider usage. Below you can find a list of common data types
used in the guideline:

* <<173, Money object>>
* <<176, Problem object>>
* <<address-fields, Address object>>


[#173]
== {MUST} use the common money object

Use the following common money structure:

[source,yaml]
----
include::../models/money-1.0.0.yaml[]
----

APIs are encouraged to include a reference to the global schema for Money.

[source,yaml]
----
SalesOrder:
  properties:
    grand_total:
      $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/money-1.0.0.yaml#/Money'
----

Please note that APIs have to treat Money as a closed data type, i.e. it's not meant to be used in an inheritance hierarchy. That means the following usage is not allowed:

[source,json]
----
{
  "amount": 19.99,
  "currency": "EUR",
  "discounted_amount": 9.99
}
----

=== Cons

* Violates the https://en.wikipedia.org/wiki/Liskov_substitution_principle[Liskov Substitution Principle]
* Breaks existing library support, e.g. https://github.com/zalando/jackson-datatype-money[Jackson Datatype Money]
* Less flexible since both amounts are coupled together, e.g. mixed currencies are impossible

A better approach is to favor https://en.wikipedia.org/wiki/Composition_over_inheritance[composition over inheritance]:

[source,json]
----
{
    "price": {
      "amount": 19.99,
      "currency": "EUR"
    },
    "discounted_price": {
      "amount": 9.99,
      "currency": "EUR"
    }
}
----

=== Pros

* No inheritance, hence no issue with the substitution principle
* Makes use of existing library support
* No coupling, i.e. mixed currencies is an option
* Prices are now self-describing, atomic values

=== Notes

Please be aware that some business cases (e.g. transactions in Bitcoin) call for a higher precision, so applications must be prepared to accept values with unlimited precision, unless explicitly stated otherwise in the API specification.

Examples for correct representations (in EUR):

* `42.20` or `42.2` = 42 Euros, 20 Cent
* `0.23` = 23 Cent
* `42.0` or `42` = 42 Euros
* `1024.42` = 1024 Euros, 42 Cent
* `1024.4225` = 1024 Euros, 42.25 Cent

Make sure that you don’t convert the "amount" field to `float` /
`double` types when implementing this interface in a specific language
or when doing calculations. Otherwise, you might lose precision.
Instead, use exact formats like Java’s
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html[`BigDecimal`].
See http://stackoverflow.com/a/3730040/342852[Stack Overflow] for more
info.

Some JSON parsers (NodeJS’s, for example) convert numbers to floats by default.
After discussing the pros and cons we’ve decided on "decimal" as our amount
format. It is not a standard OpenAPI format, but should help us to avoid parsing
numbers as float / doubles.


[#174]
== {MUST} use common field names and semantics

There exist a variety of field types that are required in multiple places. To
achieve consistency across all API implementations, you must use common field
names and semantics whenever applicable.

[[generic-fields]]
=== Generic fields

There are some data fields that come up again and again in API data:

* [[id]]{id}: the identity of the object. If used, IDs must be opaque strings
  and not numbers. IDs are unique within some documented context, are stable
  and don't change for a given object once assigned, and are never recycled
  cross entities.
* [[xyz_id]]{xyz_id}: an attribute within one object holding the identifier of
  another object must use a name that corresponds to the type of the referenced
  object or the relationship to the referenced object followed by `_id` (e.g.
  `partner_id` not `partner_number`, or `parent_node_id` for the reference to a parent
  node from a child node, even if both have the type `Node`).
  *Exception*: We use `customer_number` instead of `customer_id` for customer facing
  identification of customers due to legacy reasons. (Hint: `customer_id` used to be defined
  as internal only, technical integer key, see
  https://apis.zalando.net/redirect/5675b6ec-8934-11ea-929e-68f728c1ba70[Naming
  Decision: `customer_number` vs `customer_id` [internal link]]).
* [[created_at]]{created_at}: when the object was created. If used, this must
  be a `date-time` construct. Originally named [[created]]{created} before
  adding the <<235, naming conventions for date/time properties>>.
* [[modified_at]]{modified_at}: when the object was updated. If used, this must
  be a `date-time` construct. Originally named [[modified]]{modified} before
  adding the <<235, naming conventions for date/time properties>>.
* [[type]]{type}: the kind of thing this object is. If used, the type of this
  field should be a string. Types allow runtime information on the entity
  provided that otherwise requires examining the OpenAPI file.
* [[etag]]{etag}: the <<182, ETag>> of an <<158, embedded sub-resource>>. It
  may be used to carry the {ETag} for subsequent {PUT}/{PATCH} calls (see
  <<etag-in-result-entities>>).

Example JSON schema:

[source,yaml]
----
tree_node:
  type: object
  properties:
    id:
      description: the identifier of this node
      type: string
    created_at:
      description: when got this node created
      type: string
      format: 'date-time'
    modified_at:
      description: when got this node last updated
      type: string
      format: 'date-time'
    type:
      type: string
      enum: [ 'LEAF', 'NODE' ]
    parent_node_id:
      description: the identifier of the parent node of this node
      type: string
  example:
    id: '123435'
    created_at: '2017-04-12T23:20:50.52Z'
    modified_at: '2017-04-12T23:20:50.52Z'
    type: 'LEAF'
    parent_node_id: '534321'
----

These properties are not always strictly necessary, but making them idiomatic
allows API client developers to build up a common understanding of Zalando's
resources. There is very little utility for API consumers in having different
names or value types for these fields across APIs.


[[pagination-fields]]
=== Pagination fields

For iterating over collections (result sets) we propose to either use cursors
(see <<160>>) or simple hypertext controls (see <<161>>). To implement these
in a consistent way, we have defined a response page object pattern with the
following field semantics:

* [[self]]{self}:the link or cursor in a pagination response or object
  pointing to the same collection object or page.
* [[first]]{first}: the link or cursor in a pagination response or object
  pointing to the first collection object or page.
* [[prev]]{prev}: the link or cursor in a pagination response or object
  pointing to the previous collection object or page.
* [[next]]{next}: the link or cursor in a pagination response or object
  pointing to the next collection object or page.
* [[last]]{last}: the link or cursor in a pagination response or object
  pointing to the last collection object or page.

Pagination responses should contain the following additional array field to
transport the page content:

* [[items]]{items}: array of resources, holding all the items of the current
  page ({items} may be replaced by a resource name).

To simplify user experience, the applied query filters may be returned using
the following field (see also {GET-with-body}):

* [[query]]{query}: object containing the query filters applied in the search
  request to filter the collection resource.

As Result, the standard response page using <<160, cursors>> or <<161,
pagination links>> may be defined as follows:

[source,yaml]
----
ResponsePage:
  type: object
  required:
    - items
    - next
  properties:
    self:
      description: Pagination link|cursor pointing to the current page.
      type: string
      format: uri|cursor
    first:
      description: Pagination link|cursor pointing to the first page.
      type: string
      format: uri|cursor
    prev:
      description: Pagination link|cursor pointing to the previous page.
      type: string
      format: uri|cursor
    next:
      description: Pagination link|cursor pointing to the next page.
      type: string
      format: uri|cursor
    last:
      description: Pagination link|cursor pointing to the last page.
      type: string
      format: uri|cursor

    query:
      description: >
        Object containing the query filters applied to the collection resource.
      type: object
      properties: ...

    items:
      description: Array of collection items.
      type: array
      required: false
      items:
        type: ...
----

*Note:* While you may support cursors for {next}, {prev}, {first}, {last}, and
{self} (see <<pagination-fields>>), it is best practice to replace these with
links in favor of <<161>>.

The response page may contain additional metadata about the collection or the
current page.


[[address-fields]]
=== Address fields

Address structures play a role in different functional and use-case
contexts, including country variances. All attributes that relate to
address information should follow the naming and semantics defined
below.

[source,yaml]
----
addressee:
  description: a (natural or legal) person that gets addressed
  type: object
  properties:
    salutation:
      description: |
        a salutation and/or title used for personal contacts to some
        addressee; not to be confused with the gender information!
      type: string
      example: Mr
    first_name:
      description: |
        given name(s) or first name(s) of a person; may also include the
        middle names.
      type: string
      example: Hans Dieter
    last_name:
      description: |
        family name(s) or surname(s) of a person
      type: string
      example: Mustermann
    business_name:
      description: |
        company name of the business organization. Used when a business is
        the actual addressee; for personal shipments to office addresses, use
        `care_of` instead.
      type: string
      example: Consulting Services GmbH
  required:
    - first_name
    - last_name

address:
  description:
    an address of a location/destination
  type: object
  properties:
    care_of:
      description: |
        (aka c/o) the person that resides at the address, if different from
        addressee. E.g. used when sending a personal parcel to the
        office /someone else's home where the addressee resides temporarily
      type: string
      example: Consulting Services GmbH
    street:
      description: |
        the full street address including house number and street name
      type: string
      example: Schönhauser Allee 103
    additional:
      description: |
        further details like building name, suite, apartment number, etc.
      type: string
      example: 2. Hinterhof rechts
    city:
      description: |
        name of the city / locality
      type: string
      example: Berlin
    zip:
      description: |
        zip code or postal code
      type: string
      example: 14265
    country_code:
      description: |
        the country code according to
        [iso-3166-1-alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
      type: string
      example: DE
  required:
    - street
    - city
    - zip
    - country_code
----

Grouping and cardinality of fields in specific data types may vary based
on the specific use case (e.g. combining addressee and address fields
into a single type when modeling an address label vs distinct addressee
and address types when modeling users and their addresses).
