[[meta-information]]
= Meta Information

[#218]
== {MUST} Contain API Meta Information
API specifications must contain the following OpenAPI meta information
to allow for API management:

- `#/info/title` as (unique) identifying, functional descriptive name of the API
- `#/info/version` to distinguish API specifications versions following
  <<116, semantic rules>>
- `#/info/description` containing a proper description of the API
- `#/info/contact/{name,url,email}` containing the responsible team

Following OpenAPI extension properties *must* be provided in addition:

- `#/info/x-api-id` unique identifier of the API (<<215, see rule 215>>)
- `#/info/x-audience` intended target audience of the API (<<219, see rule 219>>)


[#116]
== {MUST} Use Semantic Versioning

OpenAPI allows to specify the API specification version in
`#/info/version`. To share a common semantic of version information we
expect API designers to comply to http://semver.org/spec/v2.0.0.html[
Semantic Versioning 2.0] rules `1` to `8` and `11` restricted to the format
<MAJOR>.<MINOR>.<PATCH> for versions as follows:

* Increment the **MAJOR** version when you make incompatible API changes
after having aligned this changes with consumers,
* Increment the **MINOR** version when you add new functionality in a
backwards-compatible manner, and
* Optionally increment the **PATCH** version when you make
backwards-compatible bug fixes or editorial changes not affecting the
functionality.

*Additional Notes:*

* *Pre-release* versions (http://semver.org#spec-item-9[rule 9]) and
*build metadata* (http://semver.org#spec-item-10[rule 10]) must not
be used in API version information.
* While patch versions are useful for fixing typos etc, API designers
are free to decide whether they increment it or not.
* API designers should consider to use API version `0.y.z`
(http://semver.org/#spec-item-4[rule 4]) for initial API design.

Example:

[source,yaml]
----
swagger: '2.0'
info:
  title: Parcel Service API
  description: API for <...>
  version: 1.3.7
  <...>
----

[#215]
== {MUST} Provide API Identifiers

Each API must be identified by an explicit, owner assigned, globally unique,
and immutable API identifier. While APIs evolve, every API aspect may change
except the API identifier. Based on the API identifier, we can track the API
life cycle and manage the history and evolution of an API as a sequence of
API specifications. For instance, we can support to check compatibility and
correct semantic versioning of an API update against previous API versions
using the https://github.com/zalando/zally[API Linter Zally]

The API identifier is provided in the `info`-block of the Open API
specification and must conform to the following specification:

[source,yaml]
----
/info/x-api-id:
  type: string
  format: urn
  pattern: ^[a-z0-9][a-z0-9-:.]{6,62}[a-z0-9]$
  description: |
    Globally unique and immutable ID required to identify the API. The API
    identifier allows to track the history and evolution of an API as a 
    sequence of API specifications.
----

It is responsibility of the API owner to ensure that the application of the
API identifier together with the semantic API <<116,version>> reflect the
expected API history.

While it is nice to use human readable API identifiers based on self-managed
URNs, it is recommend to stick to UUIDs to relief API designers from any urge
of changing the API identifier while evolving the API. Example:

[source,yaml]
----
swagger: '2.0'
info:
  x-api-id: d0184f38-b98d-11e7-9c56-68f728c1ba70
  title: Parcel Service API
  description: API for <...>
  version: 1.5.8
  <...>
----

For more information see https://docs.google.com/document/d/1lRXcTZbZMnFeTVCaazitSWxSdKXGWkOUn99Gr-huNXg[API Identifier narrative].


[#219]
== {MUST} Provide API Audience

Each API must be classified with respect to the intended target *audience*
supposed to consume the API, to facilitate differentiated standards on APIs
for discoverability, changeability, quality of design and documentation, as
well as permission granting. We differentiate the following API audience
groups with clear organisational and legal boundaries: 

*component-internal*::
  The API consumers with this audience are restricted to applications of the
  same *functional component* which typically represents a specific *product* 
  with clear functional scope and ownership 
  (see https://docs.google.com/document/d/1ZSfVkdX_Dwpz22Xl-CFXgxe1u1eY_IfTNdFNMmnGi8c/edit#heading=h.wwteqf6ovyh[details (internal link)]).
  All services of a functional component / product are owned by a specific dedicated owner
  and engineering team(s). Typical examples of component-internal APIs are APIs 
  being used by internal helper and worker services or that support service operation.
*business-unit-internal*::
  The API consumers with this audience are restricted to applications of a
  specific product portfolio owned by the same business unit.
*company-internal*::
  The API consumers with this audience are restricted to applications owned
  by the business units of the same the company (e.g. Zalando company with
  Zalando SE, Zalando Payments SE & Co. KG. etc.)
*external-partner*::
  The API consumers with this audience are restricted to applications of
  business partners of the company owning the API and the company itself.
*external-public*::
  APIs with this audience can be accessed by anyone with Internet access.

*Note:* a smaller audience group is intentionally included in the wider group
and thus does not need to be declared additionally.

The API audience is provided as API meta information in the `info`-block of
the Open API specification and must conform to the following specification:

[source,yaml]
----
#/info/x-audience:
  type: string
  x-extensible-enum:
    - component-internal
    - business-unit-internal
    - company-internal
    - external-partner
    - external-public
  description: |
    Intended target audience of the API. Relevant for standards around
    quality of design and documentation, reviews, discoverability,
    changeability, and permission granting.
----

*Note:* Exactly *one audience* per API specification is allowed. For this
reason a smaller audience group is intentionally included in the wider group
and thus does not need to be declared additionally. If parts of your API have
a different target audience, we recommend to split API specifications along
the target audience — even if this creates redundancies
(https://docs.google.com/document/d/1ff9b6oIa6dyQRyaj36-jmFdtCjWlngnGMsligR4RMIY/edit#heading=h.401bmun50mlj[rationale]).

Example:

[source,yaml]
----
swagger: '2.0'
info:
  x-audience: company-internal
  title: Parcel Helper Service API
  description: API for <...>
  version: 1.2.4
  <...>
----

For details and more information on audience groups see the
https://docs.google.com/document/d/1ff9b6oIa6dyQRyaj36-jmFdtCjWlngnGMsligR4RMIY[
API Audience narrative].
