[[api-naming]]
= API naming


[#223]
== {MUST-SHOULD} use functional naming schema

Functional naming is a powerful, yet easy way to align global resources as
_host_, _permission_, and _event names_ within an the application landscape. It
helps to preserve uniqueness of names while giving readers meaningful context
information about the addressed component. Besides, the most important aspect
is, that it allows to keep APIs stable in the case of technical and
organizational changes (Zalando for example maintains an internal naming convention).

A unique `functional-name` is assigned to each functional component serving an API. 
It is built of the domain name of the functional group the component is belonging 
to and a unique a short identifier for the functional component itself:

[source,bnf]
----
<functional-name>      ::= <functional-domain>-<functional-component>
<functional-domain>    ::= [a-z][a-z0-9-]* -- managed functional group of components
<functional-component> ::= [a-z][a-z0-9-]* -- name of API owning functional component
----

Depending on the <<219, API audience>>, you *must/should/may* follow the functional 
naming schema for <<224, hostnames>> and <<213, event names>> 
(and also <<225, permission names>>, in future) as follows:

[cols="25%,75%,options="header"]
|=========================================================
| *Functional Naming* | *Audience*
| *must*   | external-public, external-partner
| *should* | company-internal, business-unit-internal
| *may*    | component-internal
|=========================================================

Please see the following rules for detailed functional naming patterns:
* <<224>>
* <<213>>
// * <<225>>


*Internal Guideance*:  You _must_ use the simple 
https://github.bus.zalan.do/team-architecture/functional-component-registry[functional
name registry (internal link)] to register your functional name before using
it. The registry is a centralized infrastructure service to ensure uniqueness
of your functional names (and available domains -- including subdomains) and 
to support hostname DNS resolution. +
_Hint:_ Due to lexicalic restrictions of DNS names there is no specific separator 
to split a functional name into (sub) domain and component; this knowledge is only 
managed in the registry.


[#224]
== {MUST} follow naming convention for hostnames

Hostnames in APIs must, respectively should conform to the functional naming
depending on the <<219, audience>> as follows (see <<223>> for details and
`<functional-name>` definition):

[source,bnf]
-----
<hostname>             ::= <functional-hostname> | <application-hostname>

<functional-hostname>  ::= <functional-name>.zalandoapis.com
-----

*Hint:* The following convention (e.g. used by legacy STUPS infrastructure) is deprecated 
and *only* allowed for hostnames of <<219, component-internal>> APIs:

[source,bnf]
-----
<application-hostname> ::= <application-id>.<organization-unit>.zalan.do
<application-id>       ::= [a-z][a-z0-9-]*  -- application identifier
<organization-id>      ::= [a-z][a-z0-9-]*  -- organization unit identifier, e.g. team identifier
-----

*Exception:* There are legacy hostnames used for APIs with `external-partner` audience 
which may not follow this rule due to backward compatibility constraints. 
The API Linter maintains a whitelist for this exceptions (including e.g. 
`api.merchants.zalando.com` and `api-sandbox.merchants.zalando.com`).


[#129]
== {MUST} use lowercase separate words with hyphens for path segments

Example:

[source,http]
----
/shipment-orders/{shipment-order-id}
----

This applies to concrete path segments and not the names of path
parameters. For example `{shipment_order_id}` would be ok as a path
parameter.


[#130]
== {MUST} use snake_case (never camelCase) for query parameters

Examples:

[source]
----
customer_number, order_id, billing_address
----


[#132]
== {SHOULD} prefer hyphenated-pascal-case for HTTP header fields

This is for consistency in your documentation (most other headers follow
this convention). Avoid camelCase (without hyphens). Exceptions are
common abbreviations like "ID."

Examples:

[source,http]
----
Accept-Encoding
Apply-To-Redirect-Ref
Disposition-Notification-Options
Original-Message-ID
----

See also: {RFC-7230}#page-22[HTTP Headers are case-insensitive (RFC 7230)].

See <<common-headers>> and <<proprietary-headers>> sections for more guidance
on HTTP headers.


[#134]
== {MUST} pluralize resource names

Usually, a collection of resource instances is provided (at least the API 
should be ready here). The special case of a _resource singleton_ must 
be modeled as a collection with cardinality 1 including definition of 
`maxItems` = `minItems` = 1 for the returned `array` structure 
to make the cardinality constraint explicit.

**Exception:** the _pseudo identifier_ `self` used to specify a resource endpoint 
where the resource identifier is provided by authorization information (see <<143>>).


[#135]
== {SHOULD} not use /api as base path

In most cases, all resources provided by a service are part of the
public API, and therefore should be made available under the root "/"
base path.

If the service should also support non-public, internal APIs
— for specific operational support functions, for example — we encourage 
you to maintain two different API specifications and provide
<<219, API audience>>. For both APIs, you should not use `/api` as base path.

We see API's base path as a part of deployment variant configuration.
Therefore, this information has to be declared in the
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object[server object].


[#136]
== {MUST} use normalized paths without empty path segments and trailing slashes

You must not specify paths with duplicate or trailing slashes, e.g.
`/customers//addresses` or `/customers/`. As a consequence, you must also not
specify or use path variables with empty string values.

*Reasoning:* Non standard paths have no clear semantics. As a result, behavior
for non standard paths varies between different HTTP infrastructure components
and libraries. This may leads to ambiguous and unexpected results during
request handling and monitoring.

We recommend to implement services robust against clients not following this
rule. All services *should* https://en.wikipedia.org/wiki/URI_normalization[normalize]
request paths before processing by removing duplicate and trailing slashes.
Hence, the following requests should refer to the same resource:

[source,http]
----
GET /orders/{order-id}
GET /orders/{order-id}/
GET /orders//{order-id}
----

**Note:** path normalization is not supported by all framework out-of-the-box.
Services are required to support at least the normalized path while rejecting
all alternatives paths, if failing to deliver the same resource.


[#137]
== {MUST} stick to conventional query parameters

If you provide query support for searching, sorting, filtering, and
paginating, you must stick to the following naming conventions:

* [[q]]{q}: default query parameter, e.g. used by browser tab completion;
  should have an entity specific alias, e.g. sku.
* [[sort]]{sort}: comma-separated list of fields (as defined by <<154>>) to
  define the sort order. To indicate sorting direction, fields may be prefixed
  with `+` (ascending) or `-` (descending), e.g. /sales-orders?sort=+id.
* [[fields]]{fields}: field name expression to retrieve only a subset of fields
  of a resource. See <<157>> below.
* [[embed]]{embed}: field name expression to expand or embedded sub-entities,
  e.g. inside of an article entity, expand silhouette code into the silhouette
  object. Implementing {embed} correctly is difficult, so do it with care.
  See <<158>> below.
* [[offset]]{offset}: numeric offset of the first element provided on a page
  representing a collection request. See <<pagination>> section below.
* [[cursor]]{cursor}: an opaque pointer to a page, never to be inspected or
  constructed by clients. It usually (encrypted) encodes the page position,
  i.e. the identifier of the first or last page element, the pagination
  direction, and the applied query filters to recreate the collection. See
  <<cursor-based-pagination>> or <<pagination>> section below.
* [[limit]]{limit}: client suggested limit to restrict the number of entries on
  a page. See <<pagination>> section below.

