[[api-naming]]
= API Naming

[#220]
== {MUST-SHOULD} Use functional naming schema

To allow for stable APIs in the case of technical and organizational changes,
<<221, hostnames>>, <<105, permission names>>, and <213, event names>> in APIs
are strongly recommended to follow the
https://docs.google.com/document/d/1ZSfVkdX_Dwpz22Xl-CFXgxe1u1eY_IfTNdFNMmnGi8c[functional
naming schema (internal link)]. The recommendation level follows the intended
<<219, audience>> of the API as follows:

|=======================================
|*Audience*                  | *Level*
|*component-internal*        | Should
|*business-unit-internal*    | Should
|*company-internal*          | Must
|*business-partner-external* | Must
|*public-external*           | Must
|=======================================

To conduct the functional naming schema, you have to assign your application a
unique functional name that consists of a `functional-component` name within a
curated `functional-domain`. The uniqueness of this name and its consistency with
global architecture is ensured by 
https://github.bus.zalan.do/team-architecture/functional-component-registry[registering
(internal link)] for functional components.

Please see the following rules for detailed patterns:

* <<221>>
* <<105>>
* <<213>>

[#221]
== {MUST-SHOULD} Use functional naming schema for hostnames

Hostnames in APIs are recommended to conform to the functional naming (see 
<<220>> for details and registration) as follows:

[source,bnf]
----
hostname ::= <functional-domain>[-<functional-component>].zalandoapis.com

functional-domain    ::= [a-z][a-z0-9]* ; name managed by architecture team

functional-component ::= [a-z][a-z0-9-]* ; functional name of owning component
----

The `functional-domain` and `functional-component` must correspond to the
functional name of the providing application.

[#129]
== {MUST} Use lowercase separate words with hyphens for Path Segments

Example:

[source,http]
----
/shipment-orders/{shipment-order-id}
----

This applies to concrete path segments and not the names of path
parameters. For example `{shipment_order_id}` would be ok as a path
parameter.

[#130]
== {MUST} Use snake_case (never camelCase) for Query Parameters

Examples:

[source]
----
customer_number, order_id, billing_address
----

[#132]
== {SHOULD} Prefer Hyphenated-Pascal-Case for HTTP header Fields

This is for consistency in your documentation (most other headers follow
this convention). Avoid camelCase (without hyphens). Exceptions are
common abbreviations like “ID.”

Examples:

[source,http]
----
Accept-Encoding
Apply-To-Redirect-Ref
Disposition-Notification-Options
Original-Message-ID
----

See also: http://tools.ietf.org/html/rfc7230#page-22[HTTP Headers are
case-insensitive (RFC 7230)].

See <<common-headers>> and <<proprietary-headers>> sections for more guidance
on HTTP headers.

[#134]
== {MUST} Pluralize Resource Names

Usually, a collection of resource instances is provided (at least API
should be ready here). The special case of a resource singleton is a
collection with cardinality 1.

[#135]
== {MAY} Use /api as first Path Segment

In most cases, all resources provided by a service are part of the
public API, and therefore should be made available under the root “/”
base path. If the service should also support non-public, internal APIs
— for specific operational support functions, for example — add “/api”
as base path to clearly separate public and non-public API resources.

[#136]
== {MUST} Avoid Trailing Slashes

The trailing slash must not have specific semantics. Resource paths must
deliver the same results whether they have the trailing slash or not.

[#137]
== {MAY} Use Conventional Query Strings

If you provide query support for sorting, pagination, filtering
functions or other actions, use the following standardized naming
conventions:

* `q` — default query parameter (e.g. used by browser tab completion);
should have an entity specific alias, like sku
* `limit` — to restrict the number of entries. See Pagination section
below. Hint: You can use size as an alternate query string.
* `cursor` — key-based page start. See <<pagination>> section below.
* `offset` — numeric offset page start. See <<pagination>> section below.
Hint: In combination with limit, you can use page as an alternative to
offset.
* `sort` — comma-separated list of fields to sort. To indicate sorting
direction, fields may be prefixed with + (ascending) or - (descending,
default), e.g. /sales-orders?sort=+id
* `fields` — to retrieve a subset of fields. See
<<157,_Support Filtering of Resource Fields_>> below.
* `embed` — to expand embedded entities (ie.: inside of an article
entity, expand silhouette code into the silhouette object). Implementing
“expand” correctly is difficult, so do it with care.


