[[pagination]]
= Pagination

[#159]
== {MUST} Support Pagination

Access to lists of data items must support pagination to protect the service
against overload as well as for best client side iteration and batch processing
experience. This holds true for all lists that are (potentially) larger than
just a few hundred entries.

There are two well known page iteration techniques:

* https://developer.infoconnect.com/paging-results[Offset/Limit-based
  pagination]: numeric offset identifies the first page entry
* https://dev.twitter.com/overview/api/cursoring[Cursor/Limit-based] — aka
  key-based — pagination: a unique key element identifies the first page entry
  (see also https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging[Facebook’s
  guide])

The technical conception of pagination should also consider user experience
related issues. As mentioned in this
https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/[article],
jumping to a specific page is far less used than navigation via {next}/{prev}
page links (See <<161>>). This favours cursor-based over offset-based
pagination.

**Note:** To provide a consistent look and feel of pagination patterns,
you must stick to the common query parameter names defined in <<137>>.

[#160]
== {SHOULD} Prefer Cursor-Based Pagination, Avoid Offset-Based Pagination

Cursor-based pagination is usually better and more efficient when compared to
offset-based pagination. Especially when it comes to high-data volumes and/or
storage in NoSQL databases.

Before choosing cursor-based pagination, consider the following trade-offs:

* Usability/framework support:
  ** Offset-based pagination is more widely known than cursor-based pagination,
    so it has more framework support and is easier to use for API clients
* Use case - jump to a certain page:
  ** If jumping to a particular page in a range (e.g., 51 of 100) is really a
   required use case, cursor-based navigation is not feasible.
* Data changes may lead to anomalies in result pages:
  ** Offset-based pagination may create duplicates or lead to missing entries
     if rows are inserted or deleted between two subsequent paging requests.
  ** If implemented incorrectly, cursor-based pagination may fail when the
     cursor entry has been deleted before fetching the pages.
* Performance considerations - efficient server-side processing using
  offset-based pagination is hardly feasible for:
  ** Very big data sets, especially if they cannot reside in the main memory of
     the database.
  ** Sharded or NoSQL databases.
* Cursor-based navigation may not work if you need the total count of results.

*Hint:* The cursor used for pagination is an opaque pointer to a page, that
must never be inspected/constructed by clients. It usually (encrypted) encodes
the identifier of the first or last page element, the pagination direction, and
the applied query filters to recreate the collection. 

The page information for cursor-based pagination should consist of a set of
{cursors}, that besides {next} may provide support for {prev}, {first}, {last},
and {self} (see also <<pagination-fields>> for details) as follows:

[source,json]
----
{
  "cursors": {
    "self": "...",
    "first": "...",
    "prev": "...",
    "next": "...",
    "last": "..."
  },
  "items": [... ]
}
----

Further reading:

* https://dev.twitter.com/rest/public/timelines[Twitter]
* http://use-the-index-luke.com/no-offset[Use the Index, Luke]
* https://www.citusdata.com/blog/1872-joe-nelson/409-five-ways-paginate-postgres-basic-exotic[Paging
  in PostgreSQL]

[#161]
== {SHOULD} Use Pagination Links Where Applicable

To simplify client design, APIs should support <<165, simplified hypertext
controls>> for pagination over collections whenever applicable. Beside {next}
this may comprise the support for {prev}, {first}, {last}, and {self} as
http://www.iana.org/assignments/link-relations/[link relations] (see also
<<pagination-fields>> for details).

*Remark:* You should avoid providing a total count unless there is a clear
need to do so. Very often, there are significant system and performance
implications when supporting full counts. Especially, if the data set grows
and requests become complex queries and filters drive full scans. While this
is an implementation detail relative to the API, it is important to consider
the ability to support serving counts over the life of a service.

*Note:* In case of complex queries and filters, pagination links might not
work for cursor-based pagination, as the length of the link URL can exceed
system limits. In this case, the encoded {cursor} needs to be transported in
the request body (see {GET-with-body}).

If the collection consists of links to other resources, the collection
name should use http://www.iana.org/assignments/link-relations/[IANA
registered link relations] as names whenever appropriate, but use plural
form.

E.g. a service for articles could represent the collection of hyperlinks to
the `authors` of an article as follows:

[source,json]
----
{
  "self": "https://.../articles/xyz/authors?cursor=...",
  "first": "https://.../articles/xyz/authors?cursor=...",
  "prev": "https://.../articles/xyz/authors?cursor=...",
  "next": "https://.../articles/xyz/authors?cursor=...",
  "last": "https://.../articles/xyz/authors?cursor=...",
  "items": [{
      "href": "https://.../authors/...",
      "id": "123e4567-e89b-12d3-a456-426655440000",
      "name": "Kent Beck"
    }, {
      "href": "https://.../authors/...",
      "id": "987e2343-e89b-12d3-a456-426655440000",
      "name": "Mike Beedle"
    }
  ]
}
----
