[[pagination]]
= Pagination


[#159]
== {MUST} support pagination

Access to lists of data items must support pagination to protect the service
against overload as well as for best client side iteration and batch processing
experience. This holds true for all lists that are (potentially) larger than
just a few hundred entries.

There are two well known page iteration techniques:

* https://developer.infoconnect.com/paging-results[Offset/Limit-based
  pagination]: numeric offset identifies the first page entry
* https://dev.twitter.com/overview/api/cursoring[Cursor/Limit-based] — aka
  key-based — pagination: a unique key element identifies the first page entry
  (see also https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging[Facebook’s
  guide])

The technical conception of pagination should also consider user experience
related issues. As mentioned in this
https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/[article],
jumping to a specific page is far less used than navigation via {next}/{prev}
page links (See <<161>>). This favours cursor-based over offset-based
pagination.

**Note:** To provide a consistent look and feel of pagination patterns,
you must stick to the common query parameter names defined in <<137>>.


[#160]
== {SHOULD} prefer cursor-based pagination, avoid offset-based pagination

Cursor-based pagination is usually better and more efficient when compared to
offset-based pagination. Especially when it comes to high-data volumes and/or
storage in NoSQL databases.

Before choosing cursor-based pagination, consider the following trade-offs:

* Usability/framework support:
  ** Offset-based pagination is more widely known than cursor-based pagination,
    so it has more framework support and is easier to use for API clients
* Use case - jump to a certain page:
  ** If jumping to a particular page in a range (e.g., 51 of 100) is really a
   required use case, cursor-based navigation is not feasible.
* Data changes may lead to anomalies in result pages:
  ** Offset-based pagination may create duplicates or lead to missing entries
     if rows are inserted or deleted between two subsequent paging requests.
  ** If implemented incorrectly, cursor-based pagination may fail when the
     cursor entry has been deleted before fetching the pages.
* Performance considerations - efficient server-side processing using
  offset-based pagination is hardly feasible for:
  ** Very big data sets, especially if they cannot reside in the main memory of
     the database.
  ** Sharded or NoSQL databases.
* Cursor-based navigation may not work if you need the total count of results.

The {cursor} used for pagination is an opaque pointer to a page, that must
never be *inspected* or *constructed* by clients. It usually encodes (encrypts)
the page position, i.e. the identifier of the first or last page element, the
pagination direction, and the applied query filters - or a hash over these -
to safely recreate the collection (see also <<cursor-based-pagination>>).

*Note:* While you may support cursors for {next}, {prev}, {first}, {last}, and
{self} (see <<pagination-fields>>), it is best practice to replace these with
links in favor of <<161>>.


[#161]
== {SHOULD} use pagination links where applicable

To simplify client design, APIs should support <<165, simplified hypertext
controls>> for pagination over collections whenever applicable. Beside {next}
this may comprise the support for {prev}, {first}, {last}, and {self} as
{link-relations}[link relations] (see also <<pagination-fields>> for
details).

The page content is transported via {items}, while the {query} object may
contain the query filters applied to the collection resource as follows:

[source,json]
----
{
  "self": "http://my-service.zalandoapis.com/resources?cursor=<self-position>",
  "first": "http://my-service.zalandoapis.com/resources?cursor=<first-position>",
  "prev": "http://my-service.zalandoapis.com/resources?cursor=<previous-position>",
  "next": "http://my-service.zalandoapis.com/resources?cursor=<next-position>",
  "last": "http://my-service.zalandoapis.com/resources?cursor=<last-position>",
  "query": {
    "query-param-<1>": ...,
    "query-param-<n>": ...
  },
  "items": [...]
}
----

*Remark:* You should avoid providing a total count unless there is a clear
need to do so. Very often, there are significant system and performance
implications when supporting full counts. Especially, if the data set grows
and requests become complex queries and filters drive full scans. While this
is an implementation detail relative to the API, it is important to consider
the ability to support serving counts over the life of a service.
