[[performance]]
= REST Design - Performance

[#156]
== {SHOULD} use `gzip` compression

A servers and clients should support `gzip` content encoding to reduce the data
transported over the network and thereby speed up response times, unless there
is a good reason against this. Good reasons against compression are:

1. The content is already compressed, or
2. The server has not enough resources to support compression.

While `gzip` content encoding should be the default, servers must also support
unencoded content for testing. This is ensured by content negotiation using the
{Accept-Encoding} request header (see {RFC-9110}#section-12.5.3[RFC 9110
Section 12.5.3]). Successful compression is signaled via the {Content-Encoding}
response header (see {RFC-9110}#section-8.4[RFC 9110 Section 8.4]). Clients and
servers may support other compression algorithms as `compress`, `deflate`, or
`br`.

To signal server support for compression the API specification should define
both, the {Accept-Encoding} request header and the {Content-Encoding} response
header. This can be done by simply referencing the standard header definitions
as follows (see also the default definition below):

[source,yaml]
----
components:
  parameters|headers:
    Accept-Encoding:
      $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/headers-1.0.0.yaml#/Accept-Encoding'
    Content-Encoding:
      $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/headers-1.0.0.yaml#/Content-Encoding'
----

*Note:* since most server and client frameworks still **do not** support
`gzip`-compression *out-of-the-box* you need to manually activate it, e.g.
https://www.callicoder.com/configuring-spring-boot-application/#enabling-gzip-compression-in-spring-boot[Spring Boot],
or add a dedicated middleware, e.g. https://github.com/gin-contrib/gzip#usage[gin-gionic/gin].

