[[proprietary-headers]]
= Proprietary headers

This section shares definitions of proprietary headers that should be
named consistently because they address overarching service-related
concerns. Whether services support these concerns or not is optional;
therefore, the OpenAPI specification is the right place to make this
explicitly visible. Use the parameter definitions of the resource HTTP
methods.


[#183]
== {SHOULD} use only the specified proprietary Zalando headers

As a general rule, proprietary HTTP headers should be avoided. 
From a conceptual point of view, the business semantics and intent of an
operation should always be expressed via the URLs path and query parameters,
the method, and the content, but not via proprietary headers.
Headers are typically used to implement protocol processing aspects, such as flow control,
content negotiation, and authentication, and represent business agnostic 
request modifiers that provide generic context information ({RFC-7231}#section-5[RFC 7231]).

However, the exceptional usage of proprietary headers is still helpful 
when domain-specific generic context information...

. needs to be passed end to end along the service call chain (even if 
not all called services use it as input for steering service behavior 
e.g. {X-Sales-Channel} header) and/or...
. is provided by specific gateway components, for instance, our 
Fashion Shop API or Merchant API gateway. 

Below, we explicitly define the list of proprietary header exceptions usable for 
all services for passing through generic context information of our fashion domain (use case a). 

Per convention, non standardized, proprietary header names are prefixed with  `X-`. 
(Due to backward compatibility, we do not follow the Internet Engineering Task Force’s 
recommendation in {RFC-6648}[RFC 6648] to deprecate usage of  `X-` headers.)
Remember that HTTP header field names are not case-sensitive:

[cols="15%,10%,60%,15%",options="header",]
|=======================================================================
|Header field name |Type |Description |Header field value example

|[[x-flow-id]]{X-Flow-ID}|String|
For more information see <<233>>.
|GKY7oDhpSiKY_gAAAABZ_A

|[[x-tenant-id]]{X-Tenant-ID}|String|
Identifies the tenant initiated the request
to the multi tenant Zalando Platform. The {X-Tenant-ID} must be set 
according to the Business Partner ID extracted from the OAuth token when 
a request from a Business Partner hits the Zalando Platform.
|9f8b3ca3-4be5-436c-a847-9cd55460c495

|[[x-sales-channel]]{X-Sales-Channel}|String|
Sales channels are owned by retailers and represent a specific consumer segment
being addressed with a specific product assortment that is offered via CFA
retailer catalogs to consumers (see
https://digital-experience.docs.zalando.net/glossary/glossary.html[fashion platform glossary (internal link)]).
|52b96501-0f8d-43e7-82aa-8a96fab134d7

|[[x-frontend-type]]{X-Frontend-Type}|String|
Consumer facing applications (CFAs) provide business experience to their
customers via different frontend application types, for instance, mobile app
or browser. Info should be passed-through as generic aspect -- there are
diverse concerns, e.g. pushing mobiles with specific coupons, that make use of
it. Current range is mobile-app, browser, facebook-app, chat-app, email.
|mobile-app

|[[x-device-type]]{X-Device-Type}|String|
There are also use cases for steering customer experience (incl. features and
content) depending on device type. Via this header info should be passed-through
as generic aspect. Current range is smartphone, tablet, desktop, other.
|tablet

|[[x-device-os]]{X-Device-OS}|String|
On top of device type above, we even want to differ between device platform,
e.g. smartphone Android vs. iOS. Via this header info should be passed-through
as generic aspect. Current range is iOS, Android, Windows, Linux, MacOS.
|Android

|[[x-mobile-advertising-id]]{X-Mobile-Advertising-Id}|String|
It is either the 
https://developer.apple.com/documentation/adsupport/asidentifiermanager[IDFA] 
(Apple Identifier for mobile Advertising) for iOS, or the 
https://support.google.com/googleplay/android-developer/answer/6048248[GAID] 
(Google mobile Advertising Identifier) for Android. It is a unique, 
customer-resettable identifier provided by mobile device’s operating system 
to facilitate personalized advertising, and usually passed by mobile apps via http header 
when calling backend services. Called services should be ready to pass this 
parameter through when calling other services. It is not sent if the customer 
disables it in the settings for respective mobile platform.
|b89fadce-1f42-46aa-9c83-b7bc49e76e1f

|=======================================================================

*Exception:* The only exception to this guideline are the conventional
hop-by-hop `X-RateLimit-` headers which can be used as defined in <<153>>.

As part of the guidelines we sourced the OpenAPI definition of all proprietary headers;
you can simply reference it when defining the API endpoint requests e.g.
[source,yaml]
----
parameters:
- $ref: "https://opensource.zalando.com/restful-api-guidelines/models/request-headers-1.0.0.yaml#/X-Flow-ID"
- $ref: "https://opensource.zalando.com/restful-api-guidelines/models/request-headers-1.0.0.yaml#/X-Tenant-ID"
----

Response headers can be referenced in the API endpoint e.g.
[source,yaml]
----
parameters:
- $ref: "https://opensource.zalando.com/restful-api-guidelines/models/response-headers-1.0.0.yaml#/ETag"
- $ref: "https://opensource.zalando.com/restful-api-guidelines/models/response-headers-1.0.0.yaml#/Cache-Control"
----

*Hint:* This guideline does not standardize proprietary headers for 
our specific gateway components (2. use case above). 
This include, for instance, non pass-through headers `X-Zalando-Client-ID`, `X-Zalando-Request-Host`, 
`X-Zalando-Request-URI` defined by Fashion Shop API (RKeep), or `X-Consumer`, `X-Consumer-Signature`, 
`X-Consumer-Key-ID` defined by Merchant API gateway. 
All these proprietary headers are whitelisted in the API Linter (Zally) checking this rule.

[#184]
== {MUST} propagate proprietary headers

All Zalando's proprietary headers listed above are end-to-end headers
footnote:header-types[HTTP/1.1 standard ({RFC-7230}#section-6.1[RFC 7230])
defines two types of headers: end-to-end and hop-by-hop headers. End-to-end
headers must be transmitted to the ultimate recipient of a request or response.
Hop-by-hop headers, on the contrary, are meaningful for a single connection
only.]
and must be propagated to the services down the call
chain. The header names and values must remain unchanged.

For example, the values of the custom headers like {X-Device-Type} can affect
the results of queries by using device type information to influence
recommendation results. Besides, the values of the custom headers can influence
the results of the queries (e.g. the device type information influences the
recommendation results).

Sometimes the value of a proprietary header will be used as part of the entity
in a subsequent request. In such cases, the proprietary headers must still be
propagated as headers with the subsequent request, despite the duplication of
information.


[#233]
== {MUST} support {X-Flow-ID}

The {Flow-ID} is a generic parameter to be passed through service APIs and
events and written into log files and traces. A consequent usage of the
{Flow-ID} facilitates the tracking of call flows through our system and allows
the correlation of service activities initiated by a specific call. This is
extremely helpful for operational troubleshooting and log analysis. Main use
case of {Flow-ID} is to track service calls of our SaaS fashion commerce
platform and initiated internal processing flows (executed synchronously via
APIs or asynchronously via published events).


=== Data Definition

The {Flow-ID} must be passed through:

* RESTful API requests via {X-Flow-ID} proprietary header (see <<184>>)
* Published events via `flow_id` event field (see <<event-metadata, metadata>>)

The following formats are allowed:

* `UUID` ({RFC-4122}[RFC-4122])
* `base64` ({RFC-4648}[RFC-4648])
* `base64url` ({RFC-4648}#section-5[RFC-4648 Section 5])
* Random unique string restricted to the character set `[a-zA-Z0-9/+_-=]` maximal of 128 characters.

*Note:* If a legacy subsystem can only process `Flow-IDs` with a specific
format or length, it must define this restrictions in its API specification,
and be generous and remove invalid characters or cut the length to the
supported limit.

*Hint:*
In case distributed tracing is supported by {SRE-Tracing}[OpenTracing
(internal link)] you should ensure that created _spans_ are tagged using
`flow_id` — see
{SRE-Tracing}/blob/master/wg-semantic-conventions/best-practices/flowid.md[How
to Connect Log Output with OpenTracing Using Flow-IDs (internal link)] or
{SRE-Tracing}/blob/master/wg-semantic-conventions/best-practices.md[Best
practises (internal link)].

=== Service Guidance

* Services *must* support {Flow-ID} as generic input, i.e.
** RESTful API endpoints *must* support {X-Flow-ID} header in requests
** Event listeners *must* support the metadata `flow-id` from events.

+
*Note:* API-Clients *must* provide {Flow-ID} when calling a service or
producing events. If no {Flow-ID} is provided in a request or event, the
service must create a new {Flow-ID}.

* Services *must* propagate {Flow-ID}, i.e. use {Flow-ID} received
with API calls or consumed events as...
** input for all API called and events published during processing
** data field written for logging and tracing

*Note:* This rule also applies to application internal interfaces and events
not published via Nakadi (but e.g. via AWS SQS, Kinesis or service specific
DB solutions).
