[[proprietary-headers]]
= Proprietary Headers

This section shares definitions of proprietary headers that should be
named consistently because they address overarching service-related
concerns. Whether services support these concerns or not is optional;
therefore, the OpenAPI API specification is the right place to make this
explicitly visible. Use the parameter definitions of the resource HTTP
methods.

[#183]
== {MUST} Use Only the Specified Proprietary Zalando Headers

As a general rule, proprietary HTTP headers should be avoided. Still
they can be useful in cases where context needs to be passed through
multiple services in an end-to-end fashion. As such, a valid use-case
for a proprietary header is providing context information, which is not
a part of the actual API, but is needed by subsequent communication.

From a conceptual point of view, the semantics and intent of an
operation should always be expressed by URLs path and query parameters,
the method, and the content. Headers are more often used to implement
functions close to the protocol considerations, such as flow control,
content negotiation, and authentication. Thus, headers are reserved for
general context information
(https://tools.ietf.org/html/rfc7231#section-5[RFC-7231]).

`X-` headers were initially reserved for unstandardized parameters, but
the usage of `X-` headers is deprecated
(https://tools.ietf.org/html/rfc6648[RFC-6648]). This complicates the
contract definition between consumer and producer of an API following
these guidelines, since there is no aligned way of using those headers.
Because of this, the guidelines restrict which `X-` headers can be used
and how they are used.

The Internet Engineering Task Force's states in
https://tools.ietf.org/html/rfc6648[RFC-6648] that company specific
header' names should incorporate the organization's name. We aim for
backward compatibility, and therefore keep the `X-` prefix.

The following proprietary headers have been specified by this guideline
for usage so far. Remember that HTTP header field names are not
case-sensitive.

[cols="15%,10%,60%,15%",options="header",]
|=======================================================================
|Header field name |Type |Description |Header field value example

|[[x-flow-id]]{X-Flow-ID}|String|
For more information see <<233>>.
|GKY7oDhpSiKY_gAAAABZ_A

|[[x-tenant-id]]{X-Tenant-ID}|String|
Identifies the tenant initiated the request
to the multi tenant Zalando Platform. The {X-Tenant-ID} must be set 
according to the Business Partner ID extracted from the OAuth token when 
a request from a Business Partner hits the Zalando Platform. 
|9f8b3ca3-4be5-436c-a847-9cd55460c495

|[[x-sales-channel]]{X-Sales-Channel}|String|
Sales channels are owned by retailers and represent a specific consumer segment
being addressed with a specific product assortment that is offered via CFA
retailer catalogs to consumers (see
https://pages.github.bus.zalan.do/core-platform/docs/glossary/glossary.html[platform
glossary (internal link)])
|52b96501-0f8d-43e7-82aa-8a96fab134d7

|[[c-frontend-type]]{X-Frontend-Type}|String|
Consumer facing applications (CFAs) provide business experience to their
customers via different frontend application types, for instance, mobile app
or browser. Info should be passed-through as generic aspect -- there are
diverse concerns, e.g. pushing mobiles with specific coupons, that make use of
it. Current range is mobile-app, browser, facebook-app, chat-app
|mobile-app

|[[x-device-type]]{X-Device-Type}|String|
There are also use cases for steering customer experience (incl. features and
content) depending on device type. Via this header info should be passed-through
as generic aspect. Current range is smartphone, tablet, desktop, other.
|tablet

|[[x-device-os]]{X-Device-OS}|String|
On top of device type above, we even want to differ between device platform,
e.g. smartphone Android vs. iOS. Via this header info should be passed-through
as generic aspect. Current range is iOS, Android, Windows, Linux, MacOS.
|Android

|[[x-app-domain]]{X-App-Domain}|Integer|
The app domain (i.e. shop channel context) of the request. Note, app-domain is
a legacy concept that will be replaced in new platform by combinations of main
CFA concerns like retailer, sales channel, country
|16
|=======================================================================

*Exception:* The only exception to this guideline are the conventional
hop-by-hop `X-RateLimit-` headers which can be used as defined in <<153>>.

[#184]
== {MUST} Propagate Proprietary Headers

All Zalando's proprietary headers are end-to-end headers.
footnoteref:[header-types, HTTP/1.1 standard
(https://tools.ietf.org/html/rfc7230#section-6.1[RFC-7230]) defines two
types of headers: end-to-end and hop-by-hop headers. End-to-end headers
must be transmitted to the ultimate recipient of a request or response.
Hop-by-hop headers, on the contrary, are meaningful for a single
connection only.]

All headers specified above must be propagated to the services down the
call chain. The header names and values must remain unchanged.

For example, the values of the custom headers like `X-Device-Type` can
affect the results of queries by using device type information to
influence recommendation results. Besides, the values of the custom
headers can influence the results of the queries (e.g. the device type
information influences the recommendation results).

Sometimes the value of a proprietary header will be used as part of the
entity in a subsequent request. In such cases, the proprietary headers
must still be propagated as headers with the subsequent request, despite
the duplication of information.

[#233]
== {MUST} Use `X-Flow-ID`

The *Flow-Id* is a generic parameter to be through service APIs and events,
that is should be written into log files and traces. A Consequent usage of the
_Flow-Id_ facilitates the tracking of call flows through our system and allows
the correlation of service activities initiated by a specific call. This is
extremely helpful for operational troubleshooting and log analysis.

*Data Definition*

The _Flow-Id_ must be passed through:

* RESTful API requests via {X-Flow-ID} proprietary header (see <<184>>)
* Published events via `flow_id` event field (see <<event-metadata, metadata>>)

It must be an random unique string consisting of maximal 128 chars, restricted
to the character set `[a-zA-Z0-9/+]` (Base64). Services should verify the _flow
identifier_ for compliance to the before rules, but should be generous and
remove invalid characters and cut the length to the supported limit.

*Note:* If a legacy subsystem can only process _Flow-Ids_ with a specific
format or length, it must define this restrictions in its API specification.

*Hint:* In case distributed tracing is supported by {SRE-Tracing}[OpenTracing
(internal link)] you should ensure that created _spans_ are tagged using
`flow_id` (see
{SRE-Tracing}/blob/master/wg-semantic-conventions/best-practices/flowid.md[How
to Connect Log Output with OpenTracing Using FlowIDs (internal link)] or
{SRE-Tracing}/blob/master/wg-semantic-conventions/best-practices.md[Best
practises (internal link)])

*Service Guidance*

* Services *must* support _Flow-Id_ as generic input, i.e.
** RESTful API endpoints *must* support {X-Flow-ID} header in requests
** Event listeners *must* support the metadata `flow-id` from events.

*Note:*  API-Clients *must* provide _Flow-Id_ when calling a service or
producing events. If no _Flow-Id_ is provided in a request or event, the
service must create a new _Flow-Id_.

* MUST: Platform services propagate _Flow-Id_. Services use _Flow-Id_ received
with API-Calls or consumed events as...
** input for all API called and events published during processing
** data field written for logging and tracing

*Hint:* This rule also applies to application internal interfaces and events
not published via Nakadi (but e.g. via AWS SQS, Kinesis or service specific
DB solutions).
