[[resources]]
= Resources


[#138]
== {MUST} avoid actions — think about resources

REST is all about your resources, so consider the domain entities that take
part in web service interaction, and aim to model your API around these using
the standard HTTP methods as operation indicators. For instance, if an
application has to lock articles explicitly so that only one user may edit
them, create an article lock with {PUT} or {POST} instead of using a lock
action.

Request:

[source,http]
----
PUT /article-locks/{article-id}
----

The added benefit is that you already have a service for browsing and filtering
article locks.


[#139]
== {SHOULD} model complete business processes

An API should contain the complete business processes containing all resources
representing the process. This enables clients to understand the business
process, foster a consistent design of the business process, allow for
synergies from description and implementation perspective, and eliminates
implicit invisible dependencies between APIs.

In addition, it prevents services from being designed as thin wrappers around
databases, which normally tends to shift business logic to the clients.


[#140]
== {SHOULD} define _useful_ resources

As a rule of thumb resources should be defined to cover 90% of all its client's
use cases. A _useful_ resource should contain as much information as necessary,
but as little as possible. A great way to support the last 10% is to allow
clients to specify their needs for more/less information by supporting
filtering and <<157, embedding>>.


[#141]
== {MUST} keep URLs verb-free

The API describes resources, so the only place where actions should appear is
in the HTTP methods. In URLs, use only nouns. Instead of thinking of actions
(verbs), it's often helpful to think about putting a message in a letter box:
e.g., instead of having the verb _cancel_ in the url, think of sending a
message to cancel an order to the _cancellations_ letter box on the server
side.


[#142]
== {MUST} use domain-specific resource names

API resources represent elements of the application’s domain model. Using
domain-specific nomenclature for resource names helps developers to understand
the functionality and basic semantics of your resources. It also reduces the
need for further documentation outside the API definition. For example,
"sales-order-items" is superior to "order-items" in that it clearly indicates
which business object it represents. Along these lines, "items" is too general.


[#228]
== {MUST} use URL-friendly resource identifiers: [a-zA-Z0-9:._\-/]*

To simplify encoding of resource IDs in URLs, their representation must only
consist of ASCII strings using letters, numbers, underscore, minus, colon,
period, and - on rare occasions - slash.

**Note:** slashes are only allowed to build and signal resource identifiers
consisting of <<241, compound keys>>.


[#143]
== {MUST} identify resources and sub-resources via path segments

Some API resources may contain or reference sub-resources. Embedded
sub-resources, which are not top-level resources, are parts of a higher-level
resource and cannot be used outside of its scope. Sub-resources should be
referenced by their name and identifier in the path segments as follows:

[source,http]
----
/resources/{resource-id}/sub-resources/{sub-resource-id}
----

In order to improve the consumer experience, you should aim for intuitively
understandable URLs, where each sub-path is a valid reference to a resource or
a set of resources. E.g. if `/customers/12ev123bv12v/addresses/DE_100100101` is valid,
then `/customers/12ev123bv12v/addresses`, `/customers/12ev123bv12v` and
`/customers` must be valid as well in principle. E.g.:

[source,http]
----
/customers/12ev123bv12v/addresses/DE_100100101
/customers/12ev123bv12v
/shopping-carts/de:1681e6b88ec1/items/1
/shopping-carts/de:1681e6b88ec1
/content/images/9cacb4d8
/content/images
----

**Note:** resource identifiers may be build of multiple other resource
identifiers (see <<241>>).


[#241]
== {MAY} expose compound keys as resource identifiers

If a resource is best identified by a _compound key_ consisting of multiple
other resource identifiers, it is allowed to reuse the compound key in its
natural form containing slashes instead of _technical_ resource identifier in
the resource path without violating the above rule <<143>> as follows:

[source,http]
----
/resources/{compound-key-1}[delim-1]...[delim-n-1]{compound-key-n}
----

Example paths:

[source,http]
----
/shopping-carts/{country}/{session-id}
/shopping-carts/{country}/{session-id}/items/{item-id}
/api-specifications/{docker-image-id}/apis/{path}/{file-name}
/api-specifications/{repository-name}/{artifact-name}:{tag}
/article-size-advices/{sku}/{sales-channel}
----

**Warning:** Exposing a compound key as described above limits ability to
evolve the structure of the resource identifier as it is no longer opaque.

To compensate for this drawback, APIs must apply a compound key abstraction
consistently in all requests and responses parameters and attributes allowing
consumers to treat these as _technical resource identifier_ replacement. The
use of independent compound key components must be limited to search and
creation requests, as follows:

[source,http]
----
# compound key components passed as independent search query parameters
GET /article-size-advices?skus=sku-1,sku-2&sales_channel_id=sid-1
=> { "items": [{ "id": "id-1", ...  },{ "id": "id-2", ...  }] }

# opaque technical resource identifier passed as path parameter
GET /article-size-advices/id-1
=> { "id": "id-1", "sku": "sku-1", "sales_channel_id": "sid-1", "size": ... }

# compound key components passed as mandatory request fields
POST /article-size-advices { "sku": "sku-1", "sales_channel_id": "sid-1", "size": ... }
=> { "id": "id-1", "sku": "sku-1", "sales_channel_id": "sid-1", "size": ... }
----

Where `id-1` is representing the opaque provision of the compound key
`sku-1/sid-1` as technical resource identifier.

**Remark:** A compound key component may itself be used as another resource
identifier providing another resource endpoint, e.g `/article-size-advices/{sku}`.


[#145]
== {MAY} consider using (non-)nested URLs

If a sub-resource is only accessible via its parent resource and may not exist
without parent resource, consider using a nested URL structure, for instance:

[source,http]
----
/shoping-carts/de/1681e6b88ec1/cart-items/1
----

However, if the resource can be accessed directly via its unique id, then the
API should expose it as a top-level resource. For example, customer has a
collection for sales orders; however, sales orders have globally unique id and
some services may choose to access the orders directly, for instance:

[source,http]
----
/customers/1637asikzec1
/sales-orders/5273gh3k525a
----


[#144]
== {SHOULD} only use UUIDs if necessary

Generating IDs can be a scaling problem in high frequency and near real time
use cases. UUIDs solve this problem, as they can be generated without
collisions in a distributed, non-coordinated way and without additional server
round trips.

However, they also come with some disadvantages:

* pure technical key without meaning; not ready for naming or name scope
  conventions that might be helpful for pragmatic reasons, e.g. we learned to
  use names for product attributes, instead of UUIDs
* less usable, because...
* cannot be memorized and easily communicated by humans
* harder to use in debugging and logging analysis
* less convenient for consumer facing usage
* quite long: readable representation requires 36 characters and comes with
  higher memory and bandwidth consumption
* not ordered along their creation history and no indication of used id volume
* may be in conflict with additional backward compatibility support of legacy
  ids

UUIDs should be avoided when not needed for large scale id generation. Instead,
for instance, server side support with id generation can be preferred ({POST}
on id resource, followed by idempotent {PUT} on entity resource). Usage of
UUIDs is especially discouraged as primary keys of master and configuration
data, like brand-ids or attribute-ids which have low id volume but widespread
steering functionality.

Please be aware that sequential, strictly monotonically increasing numeric
identifiers may reveal critical, confidential business information, like order
volume, to non-privileged clients.

In any case, we should always use string rather than number type for
identifiers. This gives us more flexibility to evolve the identifier naming
scheme. Accordingly, if used as identifiers, UUIDs should not be qualified
using a format property.

Hint: Usually, random UUID is used - see UUID version 4 in {RFC-4122}[RFC 4122].
Though UUID version 1 also contains leading timestamps it is not reflected by
its lexicographic sorting. This deficit is addressed by
https://github.com/alizain/ulid[ULID] (Universally Unique Lexicographically
Sortable Identifier). You may favour ULID instead of UUID, for instance, for
pagination use cases ordered along creation time.


[#146]
== {SHOULD} limit number of resource types

To keep maintenance and service evolution manageable, we should follow
"functional segmentation" and "separation of concern" design principles and do
not mix different business functionalities in same API definition. In practice
this means that the number of resource types exposed via an API should be
limited. In this context a resource type is defined as a set of highly related
resources such as a collection, its members and any direct sub-resources.

For example, the resources below would be counted as three resource types, one
for customers, one for the addresses, and one for the customers' related
addresses:

[source,http]
----
/customers
/customers/{id}
/customers/{id}/preferences
/customers/{id}/addresses
/customers/{id}/addresses/{addr}
/addresses
/addresses/{addr}
----

Note that:

* We consider `/customers/{id}/preferences` part of the `/customers` resource
  type because it has a one-to-one relation to the customer without an
  additional identifier.
* We consider `/customers` and `/customers/{id}/addresses` as separate resource
  types because `/customers/{id}/addresses/{addr}` also exists with an
  additional identifier for the address.
* We consider `/addresses` and `/customers/{id}/addresses` as separate resource
  types because there's no reliable way to be sure they are the same.

Given this definition, our experience is that well defined APIs involve no more
than 4 to 8 resource types. There may be exceptions with more complex business
domains that require more resources, but you should first check if you can
split them into separate subdomains with distinct APIs.

Nevertheless one API should hold all necessary resources to model complete
business processes helping clients to understand these flows.


[#147]
== {SHOULD} limit number of sub-resource levels

There are main resources (with root url paths) and sub-resources (or _nested_
resources with non-root urls paths). Use sub-resources if their life cycle is
(loosely) coupled to the main resource, i.e. the main resource works as
collection resource of the subresource entities. You should use <= 3
sub-resource (nesting) levels -- more levels increase API complexity and url
path length. (Remember, some popular web browsers do not support URLs of more
than 2000 characters.)
