[[security]]
= Security


[#104]
== {MUST} secure endpoints with OAuth 2.0

Every API endpoint needs to be secured using OAuth 2.0. Please refer to the
https://swagger.io/docs/specification/authentication/[Authentication section] of the official
Open API specification on how to specify security definitions in your API.

The following code snippet shows how to define the authorization scheme using
a bearer token (e.g. JWT token).

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

The next code snippet applies this security scheme to all API endpoints. The bearer
token of the client must have additionally the scopes scope_1 and scope_2.

[source,yaml]
----
security:
  - BearerAuth: [ scope_1, scope_2 ]
----

[#105]
== {MUST} define and assign permissions (scopes)

APIs must define permissions to protect their resources. Thus, at least one
permission must be assigned to each endpoint. Permissions are defined as shown
in the <<104, previous section>>.

The naming schema for permissions corresponds to the naming schema for <<224,
hostnames>> and <<213, event type names>>. Please refer to <<225>> for
designing permission names.

APIs should stick to component specific permissions without resource extension
to avoid governance complexity of too many fine grained permissions. For the
majority of use cases, restricting access to specific API endpoints using read
and write is sufficient for controlling access for client types like merchant
or retailer business partners, customers or operational staff. However, in
some situations, where the API serves different types of resources for
different owners, resource specific scopes may make sense.

Some examples for standard and resource-specific permissions:

[cols="25%,20%,15%,40%",options="header",]
|=======================================================================
| Application ID | Resource ID | Access Type | Example
| `order-management` | `sales_order` | `read` | `order-management.sales_order.read`
| `order-management` | `shipment_order` | `read` | `order-management.shipment_order.read`
| `fulfillment-order` | | `write` | `fulfillment-order.write`
| `business-partner-service` | |`read` | `business-partner-service.read`
|=======================================================================

////
//Prepared change for functional permission names:

[cols="15%,15%,15%,15%,40%",options="header",]
|=======================================================================
| Domain | Component | Resource | Access Type | Example
| finance | exchange-rate | - | write | z::finance.exchange-rate.write 
| transactions | order | - | read | z::transactions.order.read
| customer | address | shipment-address | read  | z::customer.address.shipment-address.read
|=======================================================================
[cols="30%,15%,15%,40%",options="header",]
|=======================================================================
| Application | Resource | Access Type | Example
| business-partner-service | | - | read | z::business-partner-service.read
| order-management | sales_order | write | z::order-management.sales_order.write
|=======================================================================

////

After permission names are defined and the permission is declared in the 
security definition at the top of an API specification, it should be assigned 
to each API operation by specifying a
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject[security
requirement] like this:

[source,yaml]
----
paths:
 /business-partners/{partner-id}:
    get:
      summary: Retrieves information about a business partner
      security:
        - BearerAuth: [ business-partner-service.read ]
----

In very rare cases a whole API or some selected endpoints may not require
specific access control. However, to make this explicit you should assign the
`uid` pseudo permission in this case. It is the user id and always available
as OAuth2 default scope.

[source,yaml]
----
paths:
  /public-information:
    get:
      summary: Provides public information about ... 
               Accessible by any user; no permissions needed.
      security:
        - BearerAuth: [ uid ]
----

Hint: you need not explicitly define the "Authorization" header; it is a
standard header so to say implicitly defined via the security section.


[#225]
== {MUST} follow naming convention for permissions (scopes)

As long as the <<223,functional naming>> is not supported for permissions,
permission names in APIs must conform to the following naming pattern:

[source,bnf]
-----
<permission> ::= <standard-permission> |  -- should be sufficient for majority of use cases
                 <resource-permission> |  -- for special security access differentiation use cases
                 <pseudo-permission>      -- used to explicitly indicate that access is not restricted

<standard-permission> ::= <application-id>.<access-mode>
<resource-permission> ::= <application-id>.<resource-name>.<access-mode>
<pseudo-permission>   ::= uid

<application-id>      ::= [a-z][a-z0-9-]*  -- application identifier
<resource-name>       ::= [a-z][a-z0-9-]*  -- free resource identifier
<access-mode>         ::= read | write    -- might be extended in future
-----

This pattern is compatible with the previous definition.

////
//Prepared change for functional permission names:
Permission names in APIs must, respectively should conform to the functional
naming depending on the <<219, audience>> as follows (see <<223>> for details
and `<functional-name>` definition):

[source,bnf]
-----
<permission> ::= <functional-permission> |
                 <standard-permission> |  -- standard permission without functional naming
                 <resource-permission> |  -- resource permission without functional naming
                 <pseudo-permission>      -- used to indicate unrestricted access

<functional-permission> ::= z::<functional-name>[.<resource-name>].<access-mode>
<pseudo-permission>     ::= uid

<resource-name>       ::= [a-z][a-z0-9-]*  -- free resource identifier
<access-mode>         ::= read || write    -- might be extended in future
-----

The following application specific legacy convention is *only* allowed for
permissions names of <<223, internal>> APIs:

[source,bnf]
-----
<standard-permission> ::= <application-id>.<access-mode>
<resource-permission> ::= <application-id>.<resource-name>.<access-mode>

<application-id>      ::= [a-z][a-z0-9-]*  -- application identifier

-----

////
