[[security]]
= Security

[#104]
== {MUST} Secure Endpoints with OAuth 2.0

Every API endpoint needs to be secured using OAuth 2.0. Please refer to
the
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object[official
OpenAPI spec] on how to specify security definitions in you API
specification or take a look at the following example.

[source,yaml]
----
securityDefinitions:
  oauth2:
    type: oauth2
    flow: application
    tokenUrl: https://identity.zalando.com/oauth2/token
    scopes:
      fulfillment-order-service.read: Access right needed to read from the fulfillment order service.
      fulfillment-order-service.write: Access right needed to write to the fulfillment order service.      
----

The example defines OAuth2 with client credentials flow as security standard used
for authentication when accessing endpoints; additionally, there are two
API access rights defined via the scopes section for later endpoint
authorization usage - please see next section.

It makes little sense specifying the flow to retrieve OAuth tokens in
the `securityDefinitions` section, as API endpoints should not care, how
OAuth tokens were created. Unfortunately the `flow` field is mandatory
and cannot be omitted. API endpoints should always set `flow: application`
and ignore this information.

[#105]
== {MUST} Define and Assign Access Rights (Permissions)

Every API needs to define access permissions to it's resources. Every endpoint needs to have 
at least one permission assigned. Permissions are defined by name and described per API 
specification, as shown in the previous section.
The naming schema for permissions correspond to the naming schema for hostnames. Please 
refer to the following rules when creating permissions:

[source,bnf]
----
permission ::= <name-space>::<permission-name>

name-space ::= z ; fix prefix for all permissions created by Zalando business partners

permission-name ::= <functional-domain>[.<functional-component>].[<resource>].<access-type>

functional-domain ::= [a-z][a-z0-9]* ; name managed by central architecture team

functional-component ::= [a-z][a-z0-9-]* ; functional name of the component hosting the resource, the permission protects

resource ::= [a-z][a-z0-9-]* ; free identifier - resource name

access-type ::= read || write ; might be extended in future
----

The functional-domain and functional-component must be equal to the domain and 
component of the API hostname this permissions are protecting.

APIs should stick to standard permissions by default -- for the majority of use cases, 
restricting access to specific APIs (with read vs. write differentiation) is sufficient 
for controlling access for client types like merchant or retailer business partners, 
customers or operational staff. We want to avoid too many, fine grained scopes increasing 
governance complexity without real value add. In some situations, where the API serves 
different types of resources for different owners, resource specific scopes may make sense.

Some examples for standard and resource-specific permissions:

[cols="20%,20%,20%,20%,20%",options="header",]
|=======================================================================
| Domain | Component | Resource | Access Type | Example
| finance | exchange-rate | - | write | z::finance.exchange-rate.write 
| transactions | order | - | read | z::transactions.order.read
| customer | address | shipment-address | read  | z::customer.address.shipment-address.read
|=======================================================================

After permission names are defined and the permission is declared in the 
security definition at the top of an API specification, it should be assigned 
to each API operation by specifying a
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject[security
requirement] like this:

[source,yaml]
----
paths:
 /business-partners/{partner-id}:
    get:
      summary: Retrieves information about a business partner
      security:
        - oauth2:
          - z::core.business-partner.read
----

In very rare cases a whole API or some selected endpoints may not
require specific access control. However, to make this explicit you
should assign the `uid` pseudo access right scope in this case. It is
the user id and always available as OAuth2 default scope.

[source,yaml]
----
paths:
  /public-information:
    get:
      summary: Provides public information about ... 
               Accessible by any user; no access rights needed. 
      security:
        - oauth2:
          - uid
----

Hint: you need not explicitly define the "Authorization" header; it is a
standard header so to say implicitly defined via the security section.

