[[security]]
= REST Basics - Security

[#104]
== {MUST} secure endpoints

Every API endpoint must be protected and armed with authentication and authorization.
As part of the API definition you must specify how you protect your API using either the `http` typed `bearer` or `oauth2` typed security schemes defined in the
https://swagger.io/docs/specification/authentication/[OpenAPI Authentication Specification].

The majority of our APIs (especially the company internal APIs) are protected using JWT tokens provided by the platform IAM token service.
In these situations you should use the `http` typed
https://swagger.io/docs/specification/authentication/bearer-authentication/[Bearer Authentication]
security scheme -- it is based on OAuth2.0 {RFC-6750}[RFC 6750] defining the standard header
`Auhorization: Bearer <token>`.
The following code snippet shows how to define the bearer security scheme.

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

The bearer security schema can then be applied to all API endpoints, e.g. requiring the token to have `machines:read` scope for permission as follows (see also <<105>>):

[source,yaml]
----
security:
  - BearerAuth: [ machines:read ]
----

[#105]
== {MUST} define and assign permissions (scopes)

Endpoints must be equipped with permissions, if they require client authorization.

Most endpoints will require a certain permission to function properly, however some API endpoints may not require specific permissions as they return publicly available data (e.g the public app store).

The defined permissions are assigned to each API endpoint based on the security schema (see example in <<104, previous section>>) by specifying the
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securityRequirementObject[security requirement]
as follows:

[source,yaml]
----
paths:
 /machines/{machineId}:
    get:
      summary: Returns a specific machine by id
      security:
        - BearerAuth: [ machines:read ]
----

*Hint:* Following a minimal API specification approach, the
`Authorization`-header does not need to be defined on each API endpoint, since it is required and so to say implicitly defined via the security section.

[#225]
== {MUST} follow the naming convention for permissions (scopes)

All operations on and with entities within the NUPANO Suite are covered by permissions, unless they are explicitly declared "public".
If your API introduces a new entity, the following convention is to be upheld:

[source,bnf]
-----
<resource ID>         ::= [resource-name]                    -- e.g machines, organizations, apps - lowercase and plural
<access-type>         ::= create | read | update | delete    -- might be extended in future - lowercase
-----

Examples are:

[cols="25%,20%,15%,40%",options="header",]
|===
|Resource ID      | Access Type | Example      |
|machine          | read        | machines:read |
|organization     | create      | organizations:create |
|===

*Note:* APIs should stick to component specific permissions without resource extension to avoid the complexity of too many fine grained permissions.
For the majority of use cases, restricting access for specific API endpoints using read or write is sufficient.
