[[security]]
= REST Basics - Security

[#104]
== {MUST} secure endpoints

Any non public API's must be secured. Along with denoting the x-audience <<105>> and setting the correct server urls, you must specify the correct Security.

An API must be protected and armed with authentication and authorization.
As part of the API definition you must specify how you protect your API using  `http` typed `bearer` security schemes defined in the
https://swagger.io/docs/specification/authentication/[OpenAPI Authentication Specification].

The majority of our APIs (especially the company internal APIs) are protected
using JWT tokens provided by the platform IAM token service. In these situations
you should use the `http` typed
https://swagger.io/docs/specification/authentication/bearer-authentication/[Bearer Authentication]
security scheme -- it is based on OAuth2.0 {RFC-6750}[RFC 6750] defining the standard header
`Auhorization: Bearer <token>`.
The following code snippet shows how to define the bearer security scheme.

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

The bearer security schema can than be applied to an API, e.g. requiring
the token to have `linz-domains:full` scope for permission as follows (see
also <<105>>):

[source,yaml]
----
security:
  - BearerAuth: [ linz-domains:full ]
----

[#105]
== {MUST} define and assign permissions (scopes)

We currently only use the linz-domains:full permission for company-internal and component-internal audiences. The
external-public audience, doesn't need to define a scope.

The defined permission is then assigned the whole API. If a single service needs to serve multiple audiences it is best to split into separate specifications See <<219, MUST provide audience>>.

[source,yaml]
----
security:
- BearerAuth: [ linz-domains:full ]
paths:
  /public-information:
    get:
      summary: Provides public information about ...
               Accessible by any user; no permissions needed.
----




