[[security]]
= REST Basics - Security


[#109]
== {MUST} secure endpoints

Every API endpoint must be protected and armed with authentication and authorization.
As part of the API definition you must specify the  `oauth2` security scheme. Please see 
the https://swagger.io/docs/specification/authentication/oauth2/[OpenAPI OAuth 2.0 Authentication] 
for more details.

So far we support https://www.rfc-editor.org/rfc/rfc6749#section-4.4[Client Credentials Grant] 
only but will support https://swagger.io/docs/specification/authentication/openid-connect-discovery/[OpenID Connect] 
soon.

The following code snippet shows how to define the OAuth 2.0 security scheme.

[source,yaml]
----
components:
  securitySchemes:
    OAuth2:
      $ref: 'https://api.swaggerhub.com/apis/hypatos.ai/auth-service/0.0.2#/components/securitySchemes/OAuth2'
----

Please note that the OAuth2 scheme is defined in the API definition of our https://app.swaggerhub.com/apis/hypatos.ai/auth-service/[Auth Service]. 
We encourage referencing this definition in your APIs, as shown above.

The OAuth2 security schema can then be applied to all API endpoints, e.g. requiring
the access token to have `api-repository.read` scope for permission as follows (see
also <<105>>):

[source,yaml]
----
security:
  - OAuth2: [ api-repository.read ]
----





[#110]
== {MUST} define and assign permissions (scopes)

APIs must define permissions to protect their resources. Thus, at least one
permission must be assigned to each API endpoint.

Please refer to <<111>> for designing permission names and see the following examples.

[cols="25%,20%,15%,40%",options="header",]
|=======================================================================
| Application ID | Resource ID | Access Type | Example
| `order-management` | `sales-order` | `read` | `order-management.sales-order.read`
| `order-management` | `shipment-order` | `read` | `order-management.shipment-order.read`
| `fulfillment-order` | | `write` | `fulfillment-order.write`
| `business-partner-service` | |`read` | `business-partner-service.read`
|=======================================================================


*Note:* APIs should stick to component specific permissions without resource
extension to avoid the complexity of too many fine grained permissions. For the
majority of use cases, restricting access for specific API endpoints using read
or write is sufficient.

The defined permissions are than assigned to each API endpoint based on the
security schema (see example in <<109>>) by specifying the
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securityRequirementObject[security requirement]
as follows:

[source,yaml]
----
paths:
 /business-partners/{partner-id}:
    get:
      summary: Retrieves information about a business partner
      security:
        - BearerAuth: [ business-partner-service.read ]
----

In some cases a whole API or selected API endpoints may not require specific
permissions, e.g. if information is public or protected by object level
authorization. To make this explicit you should assign the `uid` pseudo
permission, that is always available as OAuth2 default scope in Zalando.

[source,yaml]
----
paths:
  /public-information:
    get:
      summary: Provides public information about ...
               Accessible by any user; no permissions needed.
      security:
        - BearerAuth: [ uid ]
----

*Hint:* Following a minimal a minimal API specification approach, the
`Authorization`-header does not need to be defined on each API endpoint, since
it is required and so to say implicitly defined via the security section.


[#111]
== {MUST} follow naming convention for permissions (scopes)

Permission names in APIs must conform to the following naming pattern:

[source,bnf]
-----
<permission> ::= <standard-permission> |  -- should be sufficient for majority of use cases
                 <resource-permission> |  -- for special security access differentiation use cases
                 <pseudo-permission>      -- used to explicitly indicate that access is not restricted

<standard-permission> ::= <application-id>.<access-mode>
<resource-permission> ::= <application-id>.<resource-name>.<access-mode>
<pseudo-permission>   ::= uid

<application-id>      ::= [a-z][a-z0-9-]*  -- application identifier
<resource-name>       ::= [a-z][a-z0-9-]*  -- free resource identifier
<access-mode>         ::= read | write    -- might be extended in future
-----

This pattern is compatible with the previous definition.
