[[security]]
= REST Basics - Security

Any non public API's must be secured; that is API's exposed via https://api.landonline.govt.nz/.
This will be imply  <<219, x-audience>> has been set to company-internal or  component-internal and <<105, scopes are set correctly>>.

[#104]
== {MUST} secure API

Non public APIs are protected using JWT Access tokens provided by the platform IAM token service (Currently Keycloak) and must be armed with authentication and authorization.

As part of the API definition you must specify that the API is protected using  `http` typed `bearer` security schemes defined in the
https://swagger.io/docs/specification/authentication/bearer-authentication/[Open API Bearer Authentication] it is based on OAuth2.0 {RFC-6750}[RFC 6750] defining the standard header
`Auhorization: Bearer <token>`.
The following code snippet shows how to define the bearer security scheme.

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

The bearer security schema can than be applied to an API, e.g. requiring
the token to have `linz-domains:full` scope for permission as follows (see
also <<105>>):

[source,yaml]
----
security:
  - BearerAuth: [ linz-domains:full ]
----

[#105]
== {MUST} define and assign permissions (scopes)

We currently only use the linz-domains:full permission for company-internal and component-internal audiences. The
external-public audience, doesn't need to define a scope.

The defined permission is then assigned the whole API. If a single service needs to serve multiple audiences it is best to split into separate specifications See <<219, MUST provide audience>>.

[source,yaml]
----
security:
- BearerAuth: [ linz-domains:full ]
paths:
  /registeredclients-only-information:
    get:
      summary: Provides information about ...
               Accessible by any user; permissions needed.
----




