[[appendix-tooling]]
[appendix]
= Tooling

This is not a part of the actual guidelines, but might be helpful for following them.
Using a tool mentioned here doesn't automatically ensure you follow the guidelines.


[[api-first-integrations]]
== API First Integrations

The following frameworks were specifically designed to support the API First workflow with OpenAPI YAML files (sorted alphabetically):

* *https://github.com/zalando/api-first-hand[Api-First-Hand]:*
  API-First Play Bootstrapping Tool for Swagger/OpenAPI specs
* *https://github.com/swagger-api/swagger-codegen[Swagger Codegen]:*
  template-driven engine to generate client code in different languages by
  parsing Swagger Resource Declaration
* *https://github.com/zalando-stups/swagger-codegen-tooling[Swagger Codegen Tooling]:*
  plugin for Maven that generates pieces of code from OpenAPI specification
* *https://github.com/zalando/intellij-swagger[Swagger Plugin for IntelliJ IDEA]:*
  plugin to help you easily edit Swagger specification files inside IntelliJ IDEA

The Swagger/OpenAPI homepage lists more
http://swagger.io/open-source-integrations/[Community-Driven Language Integrations], but most of them do not fit our API First approach.

[[support-libraries]]
== Support Libraries
Go
TODO: dewayne.richardson

Ruby/Rails
TODO: dewayne.richardson

